//>>built
define("esri/request","require dojo/_base/array dojo/_base/config dojo/_base/Deferred dojo/_base/lang dojo/_base/url dojo/_base/xhr dojo/request/xhr ./core/request/script dojo/request/iframe dojo/dom-construct dojo/io-query ./kernel ./config ./sniff ./lang ./urlUtils ./deferredUtils ./support/requestUtils".split(" "),function(sa,M,N,A,E,ta,F,ua,va,wa,ja,Z,q,xa,B,O,C,ka,aa){function V(a){a=new ta(a);return(a.host+(a.port?":"+a.port:"")).toLowerCase()}function ya(a){return this._xhr?this._xhr.getResponseHeader(a):
null}function za(a,h){var b=Z.objectToQuery(a.content);b&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+b);if(2E3<a.url.length){if("data:"!==a.url.toLowerCase().slice(0,5))return b=new A,b.reject(E.mixin(Error(),{message:"When using responseType 'image', URL length cannot exceed 2000 characters."})),b;if(3E6<a.url.length)return b=new A,b.reject(E.mixin(Error(),{message:"When using responseType 'image', data URL length cannot exceed 3000000 characters."})),b}var d=new Image;h.allowImageDataAccess&&
(d.crossOrigin=a.withCredentials?"use-credentials":"anonymous");var r=!1,t=new A(function(I){r=!0;d.onload=d.onerror=d.onabort=null;d.src=""});b=function(I){d.onload=d.onerror=d.onabort=null;r||t.reject(Error("Unable to load the resource"))};d.onload=function(){d.onload=d.onerror=d.onabort=null;r||t.resolve(this)};d.onerror=b;d.onabort=b;d.alt="";d.src=a.url;return t}function ba(a,h,b,d){var r=!1,t=!1,I=!1,k;if(O.isDefined(h))if(E.isObject(h)){r=!!h.useProxy;t=!!h.usePost;I=!!h.returnProgress;var G=
h.crossOrigin}else r=!!h;a=E.mixin({},a);delete a._credential;a._ssl&&(a.url=a.url.replace(/^http:/i,"https:"));10>B("ie")&&!Aa.test(a.url)&&(a.url=encodeURI(a.url));var x=a.content,l=a.url,u=b&&a.form,H=y;G=O.isDefined(G)?G:H.useCors;a.load=function(f){if(f){if(f.error){var w=E.mixin(Error(),f.error);w.log=!!N.isDebug}else"error"===f.status&&(w=E.mixin(Error(),f),w.log=!!N.isDebug);w&&(a.failOk=!w.log,O.isDefined(w.httpCode)||(w.httpCode=w.code))}return w||f};a.error=function(f,w){w&&w.xhr&&w.xhr.abort();
f instanceof Error||(f=E.mixin(Error(),f));f.log=!!N.isDebug;a.failOk=!f.log;H.errorHandler(f,w);return f};a._token&&(a.content=a.content||{},a.content.token=a._token);var J=0;if(x&&l){var R=Z.objectToQuery(x);J=R.length+l.length+1;B("esri-url-encodes-apostrophe")&&(J=R.replace(/'/g,"%27").length+l.length+1)}a.timeout=O.isDefined(a.timeout)?a.timeout:H.timeout;a.handleAs=a.handleAs||"json";try{var c=G&&C.canUseXhr(a.url)&&!/https?:\/\/[^\/]+\/[^\/]+\/admin\/?(\/.*)?$/i.test(a.url),g=C.hasSameOrigin(a.url,
window.location.href)||c,e=t||b||J>H.postLength?!0:!1,m=g||-1===a.handleAs.indexOf("json")||!a.callbackParamName||b?!1:!0,n=C.getProxyRule(a.url)||H.alwaysUseProxy||r||!("image"===a.handleAs&&!h.allowImageDataAccess||m&&!e||g)?!0:!1;b&&!B("esri-file-upload")&&!n&&c&&(n=!0);if(n){var z=C.getProxyUrl(l,G);var v=z.path;z._xo&&(c=!0);!e&&v.length+1+J>H.postLength&&(e=!0);a.url=v+"?"+l;if(e)a.content=E.mixin(z.query||{},x);else{var D=Z.objectToQuery(E.mixin(z.query||{},x));D&&(a.url+="?"+D);a.content=
null}}if(!m||e||n){var P=a.headers;!c||P&&P.hasOwnProperty("X-Requested-With")||(P=a.headers=P||{},P["X-Requested-With"]=null);if(b){var W=a.callbackParamName||"callback.html",la=a.callbackElementName||"textarea",S,X,Ba=u.elements?u.elements.length:0;if(x=a.content)for(S in x.token&&/\/(sharing|usrsvcs)\/(appservices|servers)\//i.test(l)&&(l+=(-1===l.indexOf("?")?"?":"\x26")+"token\x3d"+x.token,a.url=n?v+"?"+l:l,delete x.token),x){var Y=x[S];if(O.isDefined(Y)){var ca=null;for(X=0;X<Ba;X++){var ma=
u.elements[X];if(ma.name===S){ca=ma;break}}ca?ca.value=Y:d?u.append(S,Y):u.appendChild(ja.create("input",{type:"hidden",name:S,value:Y}))}}if(B("esri-file-upload")){M.forEach(u.elements,function(f){f.name===W&&u.removeChild(f)});var T=d?u:new FormData(u);if(11<=B("safari")&&"entries"in T&&"delete"in T){d=[];for(var na=T.entries(),da=na.next();!da.done;){var ea=da.value;ea[1]instanceof File&&""===ea[1].name&&d.push(ea[0]);da=na.next()}d.forEach(function(f){T["delete"](f)})}a.contentType=!1;a.postData=
T;delete a.form}else{u.enctype="multipart/form-data";9>B("ie")&&(u.encoding="multipart/form-data");u.method="post";M.some(u.elements,function(f){return f.name===W})||u.appendChild(ja.create("input",{type:"hidden",name:W,value:la}));if(-1!==l.toLowerCase().indexOf("addattachment")||-1!==l.toLowerCase().indexOf("updateattachment"))l+=(-1===l.indexOf("?")?"?":"\x26")+W+"\x3d"+la,a.url=n?v+"?"+l:l;delete a.content}}if(c&&!a.hasOwnProperty("withCredentials")&&"with-credentials"===y.useCors){v=n?v:l;var oa=
C.canUseXhr(v,!0),fa=-1<oa?y.corsEnabledServers[oa]:null;if(fa&&fa.hasOwnProperty("withCredentials"))fa.withCredentials&&(a.withCredentials=!0);else if(q.id){var pa=q.id.findServerInfo(v);pa&&pa.webTierAuth&&(a.withCredentials=!0)}}a=U?U(a):a;var qa=function(){if("image"===a.handleAs)return za(a,h);if(e){if(b&&!B("esri-file-upload")){k=new A(function(){f.cancel()});var f=wa.post(a.url,a).then(function(p){k.resolve(p)}).otherwise(function(p){k.reject(p)});k.addCallback(function(p){return a.load(p)});
k.addErrback(function(p){return a.error(p)});return k}!n&&B("safari")&&(a.url+=(-1===a.url.indexOf("?")?"?":"\x26")+"_ts\x3d"+(new Date).getTime()+Ca++);if(I){a.uploadProgress=!0;a.data=a.postData;a.query=a.content;k=new A(function(){w.cancel()});var w=ua.post(a.url,a).then(function(p){k.resolve(p)},function(p){k.reject(p)},function(p){k.progress({transferType:p.transferType,loaded:p.loaded,total:p.total})});k.addCallback(function(p){return a.load(p)});k.addErrback(function(p){return a.error(p)});
return k}return F.post(a)}return F.get(a)};return a.withCredentials&&aa.isNoCorsRequestRequired(l)?k=aa.sendNoCorsRequest(l,x).addBoth(function(){var f=qa();k.ioArgs=f.ioArgs;return f}):qa()}a=U?U(a):a;a.jsonp=a.callbackParamName;a.query=a.content;k=new A(function(){Da.cancel()});var Da=va.get(a.url,a).then(function(f){k.resolve(f)}).otherwise(function(f){k.reject(f)});k.addCallback(function(f){return a.load(f)});k.addErrback(function(f){return a.error(f)});return k}catch(f){return k=new A,k.errback(a.error(f)),
k}}function ha(a){var h=y.corsStatus,b=C.canUseXhr(a,!0);-1<b&&y.corsEnabledServers.splice(b,1);var d=new A;d.reject({log:!!N.isDebug});h[V(a)]=d.promise;return b}function ia(a){var h=y.corsStatus;try{var b=V(a);if(y.corsDetection&&y.useCors&&B("esri-cors")&&a&&-1!==a.toLowerCase().indexOf("/rest/services")&&!C.hasSameOrigin(a,window.location.href)&&!C.canUseXhr(a)){if(h[b]&&!h[b].isCanceled())return h[b];var d=new A(ka._dfdCanceller);h[b]=d.promise;var r=F.get({url:a.substring(0,a.toLowerCase().indexOf("/rest/")+
6)+"info",content:{f:"json"},failOk:!0,handleAs:"json",headers:{"X-Requested-With":null},timeout:1E3*y.corsDetectionTimeout});d._pendingDfd=r;r.then(function(t){t?(C.canUseXhr(a)||y.corsEnabledServers.push(b),d.resolve()):d.reject()},function(t){d.reject(t)});return d.promise}}catch(t){}return Ea}function ra(a){U=a}function Q(a,h,b,d){function r(c){c._pendingDfd=ba(b,d,u,l);if(!c._pendingDfd){c.ioArgs=c._pendingDfd&&c._pendingDfd.ioArgs;var g=Error("Deferred object is missing");g.log=!!N.isDebug;
c.errback(g);c._pendingDfd=null;return c}c._pendingDfd.addCallback(function(e){if(!e)return e;var m=c._pendingDfd&&c._pendingDfd.ioArgs&&c._pendingDfd.ioArgs.xhr;if(!m)return e;if(m=m.getResponseHeader("Content-Type"))if(m=m.toLowerCase(),-1===m.indexOf("text/plain")&&-1===m.indexOf("application/json"))return e;if(e instanceof ArrayBuffer&&750>=e.byteLength)m=new Blob([e]);else if(e instanceof Blob&&750>=e.size)m=e;else return e;var n=new A,z=new FileReader;z.readAsText(m);z.onloadend=function(){if(!z.error)try{var v=
JSON.parse(z.result);if(v.error)var D=v.error}catch(P){}D?(D=E.mixin(Error(),D),D.log=!!N.isDebug,null==D.httpCode&&(D.httpCode=D.code),n.reject(D)):n.resolve(e)};return n.promise}).addCallback(function(e){c.ioArgs=c._pendingDfd&&c._pendingDfd.ioArgs;d.returnFullResponse&&(e={data:e,_xhr:c.ioArgs&&c.ioArgs.xhr,getHeader:ya});c.callback(e);c._pendingDfd=null}).addErrback(function(e){if(e){var m=e.code;var n=e.subcode;var z=(z=e.messageCode)&&z.toUpperCase()}if(e&&403==m&&(4==n||e.message&&-1<e.message.toLowerCase().indexOf("ssl")&&
-1===e.message.toLowerCase().indexOf("permission"))){if(!b._ssl){b._ssl=b._sslFromServer=!0;Q(c,!0,b,d);return}}else if(e&&415==e.status){if(ha(b.url),!b._err415){b._err415=1;Q(c,!0,b,d);return}}else if(q.id&&-1!==M.indexOf(q.id._errorCodes,m)&&!q.id._isPublic(b.url)&&!I&&(403!=m||-1===M.indexOf(Fa,z)&&(!O.isDefined(n)||2==n&&b._token))){c._pendingDfd=q.id.getCredential(b.url,{token:b._token,error:e});c._pendingDfd.addCallback(function(v){b._token=v.token;b._credential=v;b._ssl=b._sslFromServer||
v.ssl;Q(c,!0,b,d)}).addErrback(function(v){c.errback(v);c._pendingDfd=null});return}c.ioArgs=c._pendingDfd&&c._pendingDfd.ioArgs;c.isFulfilled()||c.errback(e);c._pendingDfd=null}).then(null,null,function(e){c.progress(e)})}var t=b.form,I=d.disableIdentityLookup,k=d._preLookup,G=!1;if(B("esri-workers")&&!1!==y.useWorkers)if(!0===d.useWorkers||!0===y.useWorkers)G=!0;else if(d.workerOptions){var x=d.workerOptions;if(x.callback||x.worker&&x.worker.worker instanceof Worker)G=!0}var l=t&&B("esri-file-upload")&&
t instanceof FormData,u=t&&(t.elements?M.some(t.elements,function(c){return"file"===c.type}):l),H=-1!==b.url.toLowerCase().indexOf("token\x3d")||b.content&&b.content.token||u&&M.some(t.elements,function(c){return"token"===c.name})?1:0;if(!h){a.addCallback(function(c){if(c&&(/\/sharing\/rest\/accounts\/self/i.test(b.url)||/\/sharing\/rest\/portals\/self/i.test(b.url))){if(!H&&!b._token&&c.user&&c.user.username){y.webTierAuthServers.push(V(b.url));var g=y.corsEnabledServers,e=C.canUseXhr(b.url,!0),
m={host:V(b.url),withCredentials:!0};if(-1===e)g.push(m);else{var n=g[e];n instanceof RegExp?(m.host=n,g.splice(e,1,m)):"object"===typeof n?n.withCredentials=!0:g.splice(e,1,m)}}Array.isArray(c.authorizedCrossOriginNoCorsDomains)&&aa.registerNoCorsDomains(c.authorizedCrossOriginNoCorsDomains)}if(c=b._credential)if(g=(g=q.id.findServerInfo(c.server))&&g.owningSystemUrl)g=g.replace(/\/?$/,"/sharing"),(c=q.id.findCredential(g,c.userId))&&-1===q.id._getIdenticalSvcIdx(g,c)&&c.resources.splice(0,0,g)});
a.addBoth(function(c){delete b._credential;!c||B("ie")&&c.nodeType||(c._ssl=b._ssl)});var J=b.load,R=b.error;J&&a.addCallback(function(c){var g=a._pendingDfd;g=g&&g.ioArgs;return J.call(g&&g.args,c,g)});R&&a.addErrback(function(c){var g=a._pendingDfd;g=g&&g.ioArgs;return R.call(g&&g.args,c,g)})}!q.id||H||b._token||q.id._isPublic(b.url)||I&&!k||!(h=q.id.findCredential(b.url))||(b._token=h.token,b._ssl=h.ssl);G?d.workerOptions&&d.workerOptions.worker?(K||(K=F),F=d.workerOptions.worker,r(a)):sa(["./workers/RequestClient"],
function(c){K||(K=F);if(d.workerOptions){var g=d.workerOptions;F=c.getClient(g.callback,g.cbFunction)}else F=c.getClient();r(a)}):(K&&(F=K,K=null),r(a));return a}function L(a,h){a.url=C.fixUrl(a.url);h=h||{};var b=new A(ka._dfdCanceller),d=ia(a.url);b._pendingDfd=d;d.always(function(r){r&&"cancel"===r.dojoType?b.reject(r):Q(b,!1,a,h)});return b}var K=null,U,y=xa.defaults.io,Fa=["COM_0056","COM_0057","SB_0008"],Ca=0,Aa=/%[0-9A-F]{2}/i,Ea=function(){var a=new A;a.resolve();return a.promise}();L._makeRequest=
ba;L._processRequest=Q;L._disableCors=ha;L._detectCors=ia;L.setRequestPreCallback=ra;q.request=L;q._makeRequest=ba;q._processRequest=Q;q._disableCors=ha;q._detectCors=ia;q.setRequestPreCallback=ra;return L});