// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.24/esri/copyright.txt for details.//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/CircularArray ../../../../core/has ../../../../core/maybe ../../../../chunks/mat2d ../../../../chunks/mat2df32 ../../../../chunks/vec2 ../../../../chunks/vec2f32 ./enums ./Utils ./WGLTile ./collisions/MetricReader ./cpuMapped/Geometry".split(" "),function(q,r,t,g,e,u,w,x,y,z,v,n,A,B){let C=0;n=function(h){function k(a,b,c,f,l){a=h.call(this,a,b,c)||this;a.instanceId=C++;a.patchCount=0;a._renderState={current:{geometry:new Map,
metrics:null},next:null,swap:!1,swapFrames:0,locked:!1};a._patches=new t(100);a._bufferPatches=new t(100);a._lastCommitTime=0;a.transforms.labelMat2d=w.create();a._store=f;a._requestLabelUpdate=l;return a}r._inheritsLoose(k,h);var d=k.prototype;d.destroy=function(){h.prototype.destroy.call(this);this._renderState.current.geometry.forEach(a=>a.destroy())};d.getGeometry=function(a){return this._renderState.current.geometry.get(a)};d.setTransform=function(a,b){h.prototype.setTransform.call(this,a,b);
const c=this.transforms.labelMat2d;b=a.getScreenTransform(c,b);const f=y.create();x.transformMat2d(f,[this.x,this.y],b);u.fromTranslation(c,f);u.multiply(c,a.viewMat2d,c)};d.patch=function(a,b){this.patchCount++;g("esri-2d-update-debug")&&!0===a.clear&&console.debug(this.key.id,"FeatureTile:patch:clear",a.clear);a.clear&&50<=this._patches.size&&this._dropPatches();const c=a.addOrUpdate&&this.key.id!==a.addOrUpdate.tileKeyOrigin;b&&c?this._bufferPatches.enqueue(a):(a.sort=a.sort&&!b,this._patches.enqueue(a));
this.requestRender()};d.commit=function(a){if(this._lastCommitTime!==a.time){this._lastCommitTime=a.time;for(a=0;4>a;a++)this._updateMesh(),this.isReady&&this._updateBufferMesh();this._renderState.swap&&(this._swapRenderStates(),this.requestRender())}};d.lock=function(){this._renderState.locked=!0};d.unlock=function(){this._renderState.locked=!1;this._flushUpdates();this._swap()};d._swapRenderStates=function(){this._renderState.next&&(this._renderState.locked?(this._renderState.swap=!0,this.requestRender()):
(this._renderState.swap=!0,this._swap()))};d._swap=function(){this._renderState.swap&&(this._renderState.swap=!1,e.isSome(this._renderState.next)&&(this._renderState.current.geometry.forEach(a=>a.destroy()),this._renderState.current=this._renderState.next,this._renderState.next=null,this._requestLabelUpdate()))};d._flushUpdates=function(){let a=this._patches.maxSize;for(;this._patches.size&&a--;)this._updateMesh(),this._swap()};d._updateBufferMesh=function(){var a=this._bufferPatches.peek();if(!e.isSome(a)||
!a.clear||null===this._renderState.next)for(;this._bufferPatches.size;)a=this._bufferPatches.dequeue(),e.isSome(a)&&this._patchBuffer(a)};d._updateMesh=function(){const a=this._patches.dequeue();e.isSome(a)&&(!0===a.clear&&(e.isSome(this._renderState.next)&&(this._renderState.next.geometry.forEach(b=>b.destroy()),this._renderState.next=null),this._renderState.next={geometry:new Map,metrics:null},g("esri-2d-update-debug")&&console.debug(this.key.id,"FeatureTile:_updateMesh - Creating new renderState")),
this.requestRender(),this._patch(a),a.end&&(g("esri-2d-update-debug")&&console.debug(this.key.id,"FeatureTile:_updateMesh - Encountered end message"),this.ready(),this._swapRenderStates()))};d._patch=function(a){v.forEachGeometryType(b=>{this._remove(b,a.remove);this._insert(b,a,!1)})};d._patchBuffer=function(a){v.forEachGeometryType(b=>{this._insert(b,a,!0)})};d._insert=function(a,b,c){try{var f;const l=e.unwrapOr(this._renderState.next,this._renderState.current),m=null==(f=b.addOrUpdate)?void 0:
f.data[a],p=l.geometry;e.isNone(m)||(p.has(a)||(g("esri-2d-update-debug")&&console.debug(this.key.id,`FeatureTile:_insert - Creating geometry buffer ${a}`),p.set(a,new B.Geometry(a,this.stage))),g("esri-2d-update-debug")&&console.debug(this.key.id,`FeatureTile:_insert - Inserting into ${a}, version=${b.addOrUpdate.version} stride=${m.stride}`),p.get(a).insert(m,b.sort,c),a===z.WGLGeometryType.LABEL&&this._insertLabelMetrics(b.type,m.metrics,b.clear))}catch(l){}};d._insertLabelMetrics=function(a,b,
c){c=e.unwrapOr(this._renderState.next,this._renderState.current);if(!e.isNone(b))if(b=A.MetricReader.from(b),e.isNone(c.metrics))c.metrics=b;else{if("update"===a)for(a=b.getCursor();a.next();)c.metrics.delete(a.id);c.metrics.link(b)}};d._remove=function(a,b){a=e.unwrapOr(this._renderState.next,this._renderState.current).geometry.get(a);b&&b.length&&a&&(a.remove(b),this._removeLabelMetrics(b))};d._removeLabelMetrics=function(a){const {metrics:b}=e.unwrapOr(this._renderState.next,this._renderState.current);
if(!e.isNone(b)&&a.length)for(const c of a)for(;b.delete(c););};d._dropPatches=function(){const a=[];let b=!1;for(;this._patches.size;){const c=this._patches.dequeue();if(e.isNone(c))break;if(c.clear){if(b)break;b=!0}a.push(c)}this._patches.clear();a.forEach(c=>this._patches.enqueue(c))};r._createClass(k,[{key:"labelMetrics",get:function(){return this._renderState.current.metrics}},{key:"hasData",get:function(){return!!this._renderState.current.geometry.size}}]);return k}(n.WGLTile);q.FeatureTile=
n;Object.defineProperties(q,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});