jQuery(document).ready(()=>{const errorIcon=`<i class="fa fa-exclamation-circle"></i>`,errorTitle=cbsDashboardLanguage==="NL"?"Data opvragen is mislukt":"Data retrieval failed",errorText=cbsDashboardLanguage==="NL"?"De service is tijdelijk niet beschikbaar. Probeer het later opnieuw.":"The service is temporarily unavailable. Please try again later.",errorHTML=`${errorIcon} ${errorTitle}<br><br>${errorText}`;bevolkingsteller();bevolkingsgroei();regionaal();migratieachtergrond();verdeling();leeftijdDonut();woonsituatie();levensloop();if(cbsDashboardLanguage=="EN"){jQuery("#cbs-dashboard-regionaal").css("cursor","initial");}
function bevolkingsteller(){jQuery("#teller-3").html(Math.floor(Math.random()*10));jQuery("#teller-4").html(Math.floor(Math.random()*10));jQuery("#teller-5").html(Math.floor(Math.random()*10));jQuery("#teller-6").html(Math.floor(Math.random()*10));jQuery("#teller-7").html(Math.floor(Math.random()*10));jQuery("#teller-8").html(Math.floor(Math.random()*10));const timeFormat=cbsDashboardLanguage==="NL"?"nl-NL":"en-GB";jQuery("#datum-teller").html(new Date().toLocaleDateString(cbsDashboardLanguage==="NL"?"nl-NL":"en-US",{weekday:'long',year:'numeric',month:'long',day:'numeric'}));jQuery("#tijd-teller").html(new Date().toLocaleTimeString(timeFormat)+"");const refreshTime=()=>jQuery("#tijd-teller").html(new Date().toLocaleTimeString(timeFormat));let d=new Date(),dd=d.getDate(),mm=d.getMonth(),yyyy=d.getFullYear()
population=[];const baseUrl="https://www.cbs.nl/-/media/cbs/Infographics/Bevolkingsteller/";let relativepath=`${baseUrl}${yyyy}_${mm + 1}_${dd}.json`;let i=0;function getData(hideTime){jQuery.when(jQuery.getJSON(relativepath)).done((result)=>{population=result!==undefined&&result&&result;setCounter();function setCounter(){let index=Math.round((d.getHours()*3600+d.getMinutes()*60+d.getSeconds())/5),popnumber=population!==undefined&&population&&population[index],output=popnumber!==undefined&&popnumber&&popnumber.toString().split("");jQuery("#teller-1").html(output[0]);jQuery("#teller-2").html(output[1]);jQuery("#teller-3").html(output[2]);jQuery("#teller-4").html(output[3]);jQuery("#teller-5").html(output[4]);jQuery("#teller-6").html(output[5]);jQuery("#teller-7").html(output[6]);jQuery("#teller-8").html(output[7]);}
setInterval(()=>{setCounter();if(!hideTime)refreshTime();},1000);}).fail(function(){if(i==10){relativepath=`${baseUrl}2021_12_31.json`;}else{d.setDate(d.getDate()-i),dd=d.getDate(),mm=d.getMonth(),yyyy=d.getFullYear();relativepath=`${baseUrl}${yyyy}_${mm + 1}_${dd}.json`;}
let errorText1=cbsDashboardLanguage==="NL"?`Het opvragen van de${i < 11 ? " juiste" : ""} data voor de realtime prognose is mislukt.<br>Probeer het later opnieuw.`:`Retrieval of the${i < 11 ? " correct" : ""} data for the real-time forecast failed.<br>Please try again later.`;jQuery("#container-teller-text").html(`${errorIcon} ${errorTitle}<br>${errorText1}`);if(i<11){i++;getData(true);}else{jQuery("#teller-1").html("?");jQuery("#teller-2").html("?");jQuery("#teller-3").html("?");jQuery("#teller-4").html("?");jQuery("#teller-5").html("?");jQuery("#teller-6").html("?");jQuery("#teller-7").html("?");jQuery("#teller-8").html("?");}});}
getData();}
function bevolkingsgroei(){function showError(){jQuery("#unit-bevolkingsontwikkeling").html("");jQuery("#cbs-dashboard-chart-bevolkingsgroei").html(errorHTML);}
ajax("https://opendata.cbs.nl/ODataApi/odata/83474NED/Perioden?$filter=substring(Key,4,2)+eq+'JJ'&$select=Key,Status").then(function(resultPeriods){let period=resultPeriods.value.slice(-1)[0],yearString=period.Key.substring(0,4);ajax("https://opendata.cbs.nl/ODataApi/odata/83474NED/TypedDataSet?$filter=Perioden+eq+'"+
period.Key+
"'").then(function(result){if(period.Status=="Voorlopig"){yearString+="*";jQuery("#voetnoot").html(cbsDashboardLanguage=="NL"?"* Voorlopige cijfers":"* provisional figures");}
jQuery("#current-year").html(yearString);let res=result.value[0],plusMinus=res.TotaleBevolkingsgroei_7>=0?"+ ":"- ";jQuery("#totale-groei").html(plusMinus+formatNumber(res.TotaleBevolkingsgroei_7,0));let geboorte=res.LevendGeborenKinderen_2;plusMinus=geboorte>=0?"+":"\u2013";jQuery("#value-bevolkingsontwikkeling").html(plusMinus+formatNumber(Math.abs(geboorte),0));let images=[],imagesSelected=[],dataArray=[{id:"point-g",className:'top',y:parseInt(res.LevendGeborenKinderen_2),},{id:"point-o",className:'bottom',y:parseInt(res.Overledenen_3)*-1,},{id:"point-i",className:'top',y:parseInt(res.Immigratie_4),},{id:"point-e",className:'bottom',y:parseInt(res.EmigratieInclusiefAdministratieveC_5)*-1,},];let chartOptions={chart:{type:"column",margin:[0,0,0,0],events:{redraw:function(){jQuery.each(this.series[0].data,function(i,point){if(point.id=="point-g"||point.id=="point-i"){point.dataLabel.attr({x:point.plotX-point.pointWidth/2-5,y:chart.xAxis[0].height/2+15,});}else if(point.id=="point-o"||point.id=="point-e"){point.dataLabel.attr({x:point.plotX-point.pointWidth/2-5,y:point.plotY,});}
let imgWidth=55,xPosition=point.plotX+imgWidth/4;images[i].attr({x:xPosition,});imagesSelected[i].attr({x:xPosition,});});},},},plotOptions:{series:{maxPointWidth:80,states:{hover:{enabled:false,},},point:{events:{mouseOver:function(){bevolkingsontwikkelingPointHover(this.id,this.y);},},},dataLabels:{enabled:"true",formatter:function(){return this.x;},},},},colors:["#FFFFFF"],title:{text:undefined,},xAxis:{categories:cbsDashboardLanguage=="NL"?["geboorte","sterfte","immigratie","emigratie"]:["births","deaths","immigration","emigration"],},yAxis:{title:{text:undefined,},plotLines:[{value:0,zIndex:4,},],tickAmount:8,},title:{text:undefined,},tooltip:{enabled:false,},series:[{name:"Bevolkingsgroei",data:dataArray,},],legend:{enabled:false,},};const chart=Highcharts.chart("cbs-dashboard-chart-bevolkingsgroei",chartOptions);jQuery.each(chart.series[0].data,async function(i,point){if(point.id=="point-g"||point.id=="point-i"){point.dataLabel.attr({x:point.plotX-point.pointWidth/2-5,y:chart.xAxis[0].height/2+15,});}else if(point.id=="point-o"||point.id=="point-e"){point.dataLabel.attr({x:point.plotX-point.pointWidth/2-5,y:point.plotY,});}
let url="";if(point.id=="point-g"){url="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-geboorte.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-geboorte-selected.svg";}else if(point.id=="point-o"){url="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-sterfte.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-sterfte-selected.svg";}else if(point.id=="point-i"){url="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-immigratie.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-immigratie-selected.svg";}else if(point.id=="point-e"){url="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-emigratie.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/bevolkingsgroei-emigratie-selected.svg";}
let imgWidth=55;let imgHeight=55;let xPosition=point.plotX+imgWidth/10;let yPosition=point.plotY-imgHeight/1.8;if(point.id=="point-e"){yPosition=chart.xAxis[0].height/2-imgHeight/4;}else if(point.id=="point-o"){yPosition=chart.xAxis[0].height/2-imgHeight/6.5;}
let mouseOver="javascript:bevolkingsontwikkelingPointHover('"+
point.id+
"',"+
point.y+
")";images.push(chart.renderer.image(url,xPosition,yPosition,imgWidth,imgHeight).attr({zIndex:6,onmouseover:mouseOver}).add());imagesSelected.push(chart.renderer.image(urlSelected,xPosition,yPosition,imgWidth,imgHeight).attr({id:point.id+"-selected",class:"bevolkingsontwikkeling-selected",zIndex:7,}).add());});jQuery("#point-g-selected").show();fillDataTable("cbs-dashboard-chart-bevolkingsgroei","Onderwerp",null,chartOptions);}).fail(function(){showError();});}).fail(function(){showError();});}
function bevolkingsontwikkelingPointHover(id,val){jQuery(".bevolkingsontwikkeling-selected").hide();jQuery("#"+id+"-selected").show();const valueContainer=jQuery("span#value-bevolkingsontwikkeling");const unitContainer=jQuery("span#unit-bevolkingsontwikkeling");let plusMinus=val>=0?"+":"\u2013";valueContainer.html(plusMinus+formatNumber(Math.abs(val),0));switch(id){case"point-g":unitContainer.html(cbsDashboardLanguage=="NL"?"geboren":"births");break;case"point-o":unitContainer.html(cbsDashboardLanguage=="NL"?"overleden":"deaths");break;case"point-i":unitContainer.html(cbsDashboardLanguage=="NL"?"geïmmigreerd":"immigrated");break;case"point-e":unitContainer.html(cbsDashboardLanguage=="NL"?"geëmigreerd":"emigrated");break;}}
function regionaal(){function showError(){jQuery("#cbs-dashboard-map-regionaal").hide();jQuery("#cbs-dashboard-regionaal").append(`<div class="dashboard-error" style="margin-top: 50px;">${errorHTML}</div>`);}
ajax("https://opendata.cbs.nl/ODataApi/odata/70072ned/Perioden?$filter=substring(Key,4,2)+eq+'JJ'").then(function(resultPeriods){let periodeSlice=-1;createMap(periodeSlice);function createMap(periodeSlice){let period=resultPeriods.value.slice(periodeSlice)[0].Key;ajax("https://opendata.cbs.nl/ODataApi/odata/70072ned/TypedDataSet?$filter=Perioden+eq+'"+
period+
"'+and+substringof('PV',RegioS)&$select=Perioden,+RegioS,+Bevolkingsdichtheid_57").then(function(result){let res=result.value;function checkValues(row){return row.Bevolkingsdichtheid_57!=null;}
if(res.some(checkValues)){const provincies={PV20:"Groningen",PV21:"Frysl\u00e2n",PV22:"Drenthe",PV23:"Overijssel",PV24:"Flevoland",PV25:"Gelderland",PV26:"Utrecht",PV27:"Noord-Holland",PV28:"Zuid-Holland",PV29:"Zeeland",PV30:"Noord-Brabant",PV31:"Limburg",};const nClasses=5;const dichtheden=res.map(function(r){return{regio:r.RegioS.trim(),dichtheid:r.Bevolkingsdichtheid_57,};}).sort(function(a,b){return a.dichtheid-b.dichtheid;});const dichtst=dichtheden.slice(-1)[0];const range=dichtst.dichtheid-dichtheden[0].dichtheid;const step=range/nClasses;let currentClass=0;for(let r in res){let PV=res[r].RegioS.trim();let dichtheid=res[r].Bevolkingsdichtheid_57;for(c=0;c<nClasses;c++){if(dichtheid>c*step){currentClass=c;}}
jQuery("#cbs-dashboard-map-regionaal > svg").children("#"+PV).addClass("map-category-"+currentClass);}
const dichtstbevolkteProvincie="<span class='cbs-dashboard-unit'>"+
provincies[dichtst.regio]+
(cbsDashboardLanguage=="NL"?" heeft</span>":" has</span>")+
"<span>"+
formatNumber(dichtst.dichtheid,0)+
"</span>"+
(cbsDashboardLanguage=="NL"?"<span class='cbs-dashboard-unit'>inwoners per km\u00B2</span>":"<span class='cbs-dashboard-unit'>people per sq km</span>");jQuery("#value-dichtstbevolkte-provincie").html(dichtstbevolkteProvincie);jQuery("#"+dichtst.regio).get(0).parentElement.appendChild(jQuery("#"+dichtst.regio).get(0));jQuery("#"+dichtst.regio).addClass("regionaal-selected");jQuery("#cbs-dashboard-map-regionaal svg").children().on("mouseenter",function(){this.parentElement.appendChild(this);jQuery("#cbs-dashboard-map-regionaal path").removeClass("regionaal-selected");if(jQuery(this).attr("id")=="PV21"){jQuery("#PV21 path").addClass("regionaal-selected");}else{jQuery(this).addClass("regionaal-selected");}
for(i=0;i<dichtheden.length;i++){if(jQuery(this).attr("id")==dichtheden[i].regio){const selectedProvincie="<span class='cbs-dashboard-unit'>"+
provincies[dichtheden[i].regio]+
(cbsDashboardLanguage=="NL"?" heeft</span>":" has</span>")+
"<span>"+
formatNumber(dichtheden[i].dichtheid,0)+
"</span>"+
(cbsDashboardLanguage=="NL"?"<span class='cbs-dashboard-unit'>inwoners per km\u00B2</span>":"<span class='cbs-dashboard-unit'>people per sq km</span>");jQuery("#value-dichtstbevolkte-provincie").html(selectedProvincie);}}});}else{periodeSlice--;createMap(periodeSlice);}}).fail(function(){showError();});}}).fail(function(){showError();});}
function migratieachtergrond(){function showError(){jQuery("#value-migratieachtergrond").next().html(errorHTML);jQuery("#foto-migratieachtergrond").css("padding-bottom",cbsDashboardLanguage==="NL"?"65px":"110px");}
ajax("https://opendata.cbs.nl/ODataApi/odata/37325/Perioden/$count").then(function(count){ajax("https://opendata.cbs.nl/ODataApi/odata/37325/Perioden?$skip="+(count-1)+"&$select=Key").then(function(resultPeriod){periode=resultPeriod.value[0].Key;ajax("https://opendata.cbs.nl/ODataApi/odata/37325/TypedDataSet?$filter=Perioden+eq+'"+periode+"'+and+Geslacht+eq+'T001038'+and+Leeftijd+eq+'10000'+and+BurgerlijkeStaat+eq+'T001019'+and+Generatie+eq+'T001040'+and+(Migratieachtergrond+eq+'T001040'+or+Migratieachtergrond+eq+'2012605')&$select=Bevolking_1,Migratieachtergrond").then(function(result){let res=result.value;let percentage=0;let totaal,migratie;for(i=0;i<res.length;i++){if(res[i].Migratieachtergrond=="T001040"){totaal=res[i].Bevolking_1;}else{migratie=res[i].Bevolking_1;}}
if(totaal>0&&migratie>0){percentage=cbsDashboardLanguage=="NL"?formatNumber((migratie/totaal)*100,1):((migratie/totaal)*100).toFixed(1);}
jQuery("#value-migratieachtergrond").html(percentage+"%");}).fail(function(){showError();});}).fail(function(){showError();});}).fail(function(){showError();});}
function verdeling(){function showError(){jQuery("#cbs-dashboard-chart-verdeling").html(errorHTML).css("text-align","left");}
ajax("https://opendata.cbs.nl/ODataApi/odata/37713/Perioden/$count").then(function(count){ajax("https://opendata.cbs.nl/ODataApi/odata/37713/Perioden?$skip="+(count-1)+"&$select=Key").then(function(resultPeriod){periode=resultPeriod.value[0].Key;ajax("https://opendata.cbs.nl/ODataApi/odata/37713/TypedDataSet?$filter=Perioden+eq+'"+periode+"'+and+Leeftijd+eq+%2710000%27+and+Migratieachtergrond+eq+%27T001040%27+and+substringof(%27NL%27,RegioS)&$select=Mannen_2,Vrouwen_3").then(function(result){const res=result.value[0];jQuery("#vrouwen").html(cbsDashboardLanguage=="NL"?formatNumber(res.Vrouwen_3/1000000,1)+" mln":(res.Vrouwen_3/1000000).toFixed(1)+" million");jQuery("#mannen").html(cbsDashboardLanguage=="NL"?formatNumber(res.Mannen_2/1000000,1)+" mln":(res.Mannen_2/1000000).toFixed(1)+" million");}).fail(function(){showError();});}).fail(function(){showError();});}).fail(function(){showError();});}
function woonsituatie(){function showError(){jQuery("#value-alleen-wonen").next().html(errorHTML);jQuery("#foto-woonsituatie").css("padding-bottom",cbsDashboardLanguage==="NL"?"63px":"83px");}
ajax("https://opendata.cbs.nl/ODataApi/odata/37620/Perioden/$count").then(function(count){ajax("https://opendata.cbs.nl/ODataApi/odata/37620/Perioden?$skip="+(count-1)+"&$select=Key").then(function(resultPeriod){periode=resultPeriod.value[0].Key;ajax("https://opendata.cbs.nl/ODataApi/odata/37620/TypedDataSet?$filter=Perioden+eq+'"+periode+"'+and+Geslacht+eq+%27T001038+%27+and+Leeftijd+eq+%2710000%27&$select=Alleenstaand_4").then(function(result){let res=result.value[0];jQuery("#value-alleen-wonen").html(cbsDashboardLanguage=="NL"?formatNumber(res.Alleenstaand_4/1000000,1)+" mln":(res.Alleenstaand_4/1000000).toFixed(1)+" million");}).fail(function(){showError();});}).fail(function(){showError();});}).fail(function(){showError();});}
function leeftijdDonut(){function showError(){jQuery("#cbs-dashboard-leeftijd").hide();jQuery("#value-leeftijd").html(errorHTML).addClass("dashboard-error").css("padding",cbsDashboardLanguage==="NL"?"43px 0":"53px 0");}
const leeftijdsgroepen=[12,13,40,34];const leeftijdsgroepenNamen=cbsDashboardLanguage=="NL"?["jonger dan 12","12 tot 25 jaar","25 tot 65 jaar","65 en ouder"]:["under 12 yrs","12 to 25 yrs","25 to 65 yrs","65 yrs and over"];let leeftijdsgroepenSum=[],jongeren;let geslacht,burgerlijkeStaat,bevolking,periode,leeftijden;let leeftijdQuery="";for(let i=0;i<100;i++){leeftijdQuery+="Title+eq+'"+i+" jaar"+(i!=99?"'+or+":" of ouder'");}
ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/Perioden/$count").then(function(count){jQuery.when(ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/Perioden?$skip="+(count-1)+"&$select=Key"),ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/Geslacht?$filter=Title+eq+'Totaal mannen en vrouwen'&$select=Key"),ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/BurgerlijkeStaat?$filter=Title+eq+'Totaal burgerlijke staat'&$select=Key"),ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/Leeftijd?$filter="+leeftijdQuery+"&$select=Key"),ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/DataProperties?$filter=Type+eq+'Topic'&$select=Key")).done(function(p,g,bs,l,bv){periode=p[0].value[0].Key;geslacht=g[0].value[0].Key;burgerlijkeStaat=bs[0].value[0].Key;leeftijden=l[0].value.map(function(lft){return lft.Key;});bevolking=bv[0].value[0].Key;leeftijdQuery="(";leeftijden.forEach(function(lft,i){leeftijdQuery+="Leeftijd+eq+'"+
lft+
(i!=leeftijden.length-1?"'+or+":"'");});leeftijdQuery+=")";ajax("https://opendata.cbs.nl/ODataApi/odata/7461bev/TypedDataSet?$filter=Perioden+eq+'"+periode+"'+and+Geslacht+eq+'"+geslacht+"'+and+BurgerlijkeStaat+eq+'"+burgerlijkeStaat+"'+and+"+leeftijdQuery+"&$select=Leeftijd,+"+bevolking).then(function(data){data=data.value;let currentIndex=0;leeftijdsgroepen.forEach(function(lftG,index){let currentGroepSum=0;for(var i=currentIndex;i<currentIndex+lftG;i++){currentGroepSum+=data[i][bevolking];}
currentIndex+=lftG;leeftijdsgroepenSum.push({name:leeftijdsgroepenNamen[index],y:currentGroepSum,});});let chartOptions={chart:{type:"pie",margin:[0,0,0,0],},plotOptions:{series:{dataLabels:{enabled:false,valueDecimals:1,},states:{hover:{enabled:false,},},point:{events:{mouseOver:function(){jQuery("#leeftijd").text(this.percentage.toLocaleString("nl-NL",{minimumFractionDigits:0,maximumFractionDigits:0}).replace(/\./g," ")+"%");jQuery("#unit-leeftijd").text(this.name);this.graphic.toFront();},},},},},title:{text:undefined,},tooltip:{enabled:false,},series:[{name:"Leeftijd",data:leeftijdsgroepenSum,},],legend:{enabled:false,},};let chart=Highcharts.chart("cbs-dashboard-chart-leeftijd",chartOptions);jongeren=chart.series[0].points.find(function(p){return p.name==(cbsDashboardLanguage=="NL"?"12 tot 25 jaar":"12 to 25 yrs");});jQuery("#leeftijd").text(jongeren.percentage.toLocaleString("nl-NL",{minimumFractionDigits:0,maximumFractionDigits:0}).replace(/\./g," ")+"%");jQuery("#unit-leeftijd").text(jongeren.name);jQuery("#cbs-dashboard-chart-leeftijd .highcharts-color-1").get(0).parentElement.appendChild(jQuery("#cbs-dashboard-chart-leeftijd .highcharts-color-1").get(0));jQuery("#cbs-dashboard-chart-leeftijd .highcharts-color-1").addClass("leeftijd-selected");jQuery("#cbs-dashboard-chart-leeftijd .highcharts-point").on("mouseover",function(){jQuery("#cbs-dashboard-chart-leeftijd").find(".leeftijd-selected").removeClass("leeftijd-selected");jQuery(this).addClass("leeftijd-selected");});}).fail(function(){showError();});}).fail(function(){showError();});}).fail(function(){showError();});}
function levensloop(){function showError(){jQuery("#cbs-dashboard-chart-levensloop").html(errorHTML).css("margin","31px 0 0 0")}
jQuery.when(ajax("https://opendata.cbs.nl/ODataApi/odata/37422ned/Perioden/$count"),ajax("https://opendata.cbs.nl/ODataApi/odata/37772ned/Perioden/$count"),ajax("https://opendata.cbs.nl/ODataApi/odata/37979ned/Perioden/$count")).done(function(countG,countH,countO){jQuery.when(ajax("https://opendata.cbs.nl/ODataApi/odata/37422ned/Perioden?$skip="+(countG[0]-1)+"&$select=Key"),ajax("https://opendata.cbs.nl/ODataApi/odata/37772ned/Perioden?$skip="+(countH[0]-1)+"&$select=Key"),ajax("https://opendata.cbs.nl/ODataApi/odata/37979ned/Perioden?$skip="+(countO[0]-1)+"&$select=Key")).done(function(resultPeriodG,resultPeriodH,resultPeriodO){let periode;if(resultPeriodG[0].value[0].Key==resultPeriodH[0].value[0].Key&&resultPeriodG[0].value[0].Key==resultPeriodO[0].value[0].Key){periode=resultPeriodG[0].value[0].Key;}else{periode=Math.min(parseInt(resultPeriodG[0].value[0].Key.substring(0,4)),parseInt(resultPeriodH[0].value[0].Key.substring(0,4)),parseInt(resultPeriodO[0].value[0].Key.substring(0,4)))+"JJ00";}
jQuery.when(ajax("https://opendata.cbs.nl/ODataApi/odata/37422ned/TypedDataSet?$filter=Perioden+eq+'"+periode+"'&$select=Perioden,GemiddeldAantal1eKinderenPerVrouw_42,GemiddeldAantal1eKinderenPerMan_47,Bij1eKind_49,Bij1eKindVanDeMoeder_54"),ajax("https://opendata.cbs.nl/ODataApi/odata/37772ned/TypedDataSet?$filter=Perioden+eq+'"+periode+"'&$select=Perioden,TotaalMannen_6,TotaalVrouwen_11,TotaalMannen_26,TotaalVrouwen_31,Gescheiden_30,Gescheiden_35"),ajax("https://opendata.cbs.nl/ODataApi/odata/37979ned/TypedDataSet?$filter=Geslacht+eq+'T001038'+and+Perioden+eq+'"+periode+"'&$select=Geslacht,Perioden,GemiddeldeLeeftijdBijOverlijden_13")).done(function(resultGeboren,resultHuwelijk,resultOverleden){let images=[],imagesSelected=[],labels=[],resG=resultGeboren[0].value[0],gemLeeftijd1eKind=resG.Bij1eKind_49;let resH=resultHuwelijk[0].value[0],gemLeeftijdHuwelijk=(resH.TotaalMannen_6*resH.TotaalMannen_26+
resH.TotaalVrouwen_11*resH.TotaalVrouwen_31)/
(resH.TotaalMannen_6+resH.TotaalVrouwen_11);let gemLeeftijdGescheiden=(resH.TotaalMannen_6*resH.Gescheiden_30+
resH.TotaalVrouwen_11*resH.Gescheiden_35)/
(resH.TotaalMannen_6+resH.TotaalVrouwen_11);let resO=resultOverleden[0]&&resultOverleden[0].value[0],gemLeeftijdOverlijden=resO&&resO.GemiddeldeLeeftijdBijOverlijden_13;let chartOptions={chart:{type:"column",margin:[0,0,0,0],events:{redraw:function(){jQuery.each(this.series[0].data,function(i,point){if(i>0&&i<5){let index=i-1;let imgWidth=55;if(point.id=="point-kind"){xPosition=point.plotX-imgWidth/1.7;}else if(point.id=="point-overlijden"){xPosition=point.plotX-imgWidth/2.1;}else if(point.id=="point-scheiden"){xPosition=point.plotX-imgWidth/3;}else if(point.id=="point-huwelijk"){xPosition=point.plotX-imgWidth/3;}
images[index].attr({x:xPosition,});imagesSelected[index].attr({x:xPosition,});}else{if(point.id=="point-0"){labels[0].attr({x:point.plotX});}else if(point.id=="point-100"){labels[1].attr({x:point.plotX-52});}}});},},},plotOptions:{series:{maxPointWidth:1,states:{hover:{enabled:false,},},point:{events:{mouseOver:function(){levensloopPointHover(this.id,this.x);},},},},},colors:["#FFFFFF"],xAxis:{floor:3,ceiling:97.5,tickLength:0,tickmarkPlacement:"on",labels:{x:25,},},yAxis:{title:{text:undefined,},plotLines:[{value:0,zIndex:4,},],gridLineWidth:0,tickInterval:3,},title:{text:undefined,},tooltip:{enabled:false,},series:[{data:[{x:0,y:-0.4,name:"0 jaar",id:"point-0",},{x:gemLeeftijd1eKind,y:1,name:"Gemiddelde leeftijd eerste kind",id:"point-kind",},{x:gemLeeftijdHuwelijk,y:-1,name:"Gemiddelde leeftijd eerste huwelijk",id:"point-huwelijk",},{x:gemLeeftijdGescheiden,y:1,name:"Gemiddelde leeftijd gescheiden",id:"point-scheiden",},{x:gemLeeftijdOverlijden,y:-1,name:"Gemiddelde leeftijd overlijden",id:"point-overlijden",},{x:100,y:-0.4,name:"100 jaar",id:"point-100",},],},],legend:{enabled:false,},};let chart=Highcharts.chart("cbs-dashboard-chart-levensloop",chartOptions);jQuery("#levensloop").html(cbsDashboardLanguage=="NL"?gemLeeftijd1eKind.toLocaleString("nl-NL",{minimumFractionDigits:1,maximumFractionDigits:1,}):gemLeeftijd1eKind.toFixed(1));jQuery("#unit-levensloop").html(cbsDashboardLanguage=="NL"?"jaar: 1e kind vrouw":"yrs: first child");jQuery.each(chart.series[0].data,async function(i,point){if(point.id=="point-0"){labels.push(chart.renderer.text(cbsDashboardLanguage=="NL"?"0 jaar":"0 yrs",point.plotX,point.plotY+14).css({fontSize:"0.9rem",color:"#82045e",}).add());}else if(point.id=="point-100"){labels.push(chart.renderer.text(cbsDashboardLanguage=="NL"?"100 jaar":"100 yrs",cbsDashboardLanguage=="NL"?point.plotX-52:point.plotX-42,point.plotY+14).css({fontSize:"0.9rem",color:"#82045e",}).add());}else{let url="",urlSelected="";if(point.id=="point-kind"){url="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-geboorte.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-geboorte-selected.svg";}else if(point.id=="point-huwelijk"){url="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-trouwen.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-trouwen-selected.svg";}else if(point.id=="point-scheiden"){url="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-scheiden.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-scheiden-selected.svg";}else if(point.id=="point-overlijden"){url="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-sterfte.svg";urlSelected="/-/media/cbs/infographics/Dashboard-bevolking/levensloop-sterfte-selected.svg";}
let imgWidth=55,imgHeight=55,xPosition,yPosition;if(point.id=="point-kind"){xPosition=point.plotX-imgWidth/1.7;}else if(point.id=="point-overlijden"){xPosition=point.plotX-imgWidth/2.1;}else if(point.id=="point-scheiden"){xPosition=point.plotX-imgWidth/3;}else if(point.id=="point-huwelijk"){xPosition=point.plotX-imgWidth/3;}
if(point.id=="point-kind"){yPosition=point.plotY-imgHeight/1.4;}else if(point.id=="point-scheiden"){yPosition=point.plotY-imgHeight/1.8;}else if(point.id=="point-overlijden"||point.id=="point-huwelijk"){yPosition=point.plotY-imgHeight/3.5;}
let mouseOver="javascript:levensloopPointHover('"+
point.id+
"',"+
point.x+
"); ";images.push(chart.renderer.image(url,xPosition,yPosition,imgWidth,imgHeight).attr({id:point.id,zIndex:6,onmouseover:mouseOver,}).add());imagesSelected.push(chart.renderer.image(urlSelected,xPosition,yPosition,imgWidth,imgHeight).attr({id:point.id+"-selected",class:"levensloop-selected",zIndex:7,}).add());}});jQuery("#point-kind-selected").show();}).fail(function(){showError();});}).fail(function(){showError();});}).fail(function(){showError();});}
function levensloopPointHover(id,val){jQuery(".levensloop-selected").hide();jQuery("#"+id+"-selected").show();jQuery("div#levensloop").html(cbsDashboardLanguage=="NL"?formatNumber(val,1):val.toFixed(1));switch(id){case"point-kind":jQuery("span#unit-levensloop").html(cbsDashboardLanguage=="NL"?"jaar: 1e kind vrouw":"yrs: first child");break;case"point-huwelijk":jQuery("span#unit-levensloop").html(cbsDashboardLanguage=="NL"?"jaar: trouwen":"yrs: wedding");break;case"point-scheiden":jQuery("span#unit-levensloop").html(cbsDashboardLanguage=="NL"?"jaar: scheiden":"yrs: divorce");break;case"point-overlijden":jQuery("span#unit-levensloop").html(cbsDashboardLanguage=="NL"?"jaar: overlijden":"yrs: death");break;}}});