/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/print/print.js. */
!function(e){"function"==typeof define&&define.amd?define(e):e()}((function(){"use strict";(Drupal=>{Drupal.behaviors.print={attach(e){(e.parentNode||e).querySelectorAll(".js-print").once("print").forEach((e=>{e.addEventListener("click",(e=>{window.print(),e.preventDefault()}),!1)}))}}})(Drupal)}));
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/print/print.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/debounce.js. */
Drupal.debounce=function(func,wait,immediate){var timeout;var result;return function(){for(var _len=arguments.length,args=new Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}
var context=this;var later=function later(){timeout=null;if(!immediate){result=func.apply(context,args);}};var callNow=immediate&&!timeout;clearTimeout(timeout);timeout=setTimeout(later,wait);if(callNow){result=func.apply(context,args);}
return result;};};
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/debounce.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/jquery.once.bc.js. */
(function($,once){var deprecatedMessageSuffix="is deprecated in Drupal 9.3.0 and will be removed in Drupal 10.0.0. Use the core/once library instead. See https://www.drupal.org/node/3158256";var originalJQOnce=$.fn.once;var originalJQRemoveOnce=$.fn.removeOnce;$.fn.once=function jQueryOnce(id){Drupal.deprecationError({message:"jQuery.once() ".concat(deprecatedMessageSuffix)});return originalJQOnce.apply(this,[id]);};$.fn.removeOnce=function jQueryRemoveOnce(id){Drupal.deprecationError({message:"jQuery.removeOnce() ".concat(deprecatedMessageSuffix)});return originalJQRemoveOnce.apply(this,[id]);};var drupalOnce=once;function augmentedOnce(id,selector,context){originalJQOnce.apply($(selector,context),[id]);return drupalOnce(id,selector,context);}
function remove(id,selector,context){originalJQRemoveOnce.apply($(selector,context),[id]);return drupalOnce.remove(id,selector,context);}
window.once=Object.assign(augmentedOnce,drupalOnce,{remove:remove});})(jQuery,once);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/jquery.once.bc.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/form.js. */
(function($,Drupal,debounce){$.fn.drupalGetSummary=function(){var callback=this.data('summaryCallback');return this[0]&&callback?callback(this[0]).trim():'';};$.fn.drupalSetSummary=function(callback){var self=this;if(typeof callback!=='function'){var val=callback;callback=function callback(){return val;};}
return this.data('summaryCallback',callback).off('formUpdated.summary').on('formUpdated.summary',function(){self.trigger('summaryUpdated');}).trigger('summaryUpdated');};Drupal.behaviors.formSingleSubmit={attach:function attach(){function onFormSubmit(e){var $form=$(e.currentTarget);var formValues=$form.serialize();var previousValues=$form.attr('data-drupal-form-submit-last');if(previousValues===formValues){e.preventDefault();}else{$form.attr('data-drupal-form-submit-last',formValues);}}
$(once('form-single-submit','body')).on('submit.singleSubmit','form:not([method~="GET"])',onFormSubmit);}};function triggerFormUpdated(element){$(element).trigger('formUpdated');}
function fieldsList(form){var $fieldList=$(form).find('[name]').map(function(index,element){return element.getAttribute('id');});return $.makeArray($fieldList);}
Drupal.behaviors.formUpdated={attach:function attach(context){var $context=$(context);var contextIsForm=$context.is('form');var $forms=$(once('form-updated',contextIsForm?$context:$context.find('form')));var formFields;if($forms.length){$.makeArray($forms).forEach(function(form){var events='change.formUpdated input.formUpdated ';var eventHandler=debounce(function(event){triggerFormUpdated(event.target);},300);formFields=fieldsList(form).join(',');form.setAttribute('data-drupal-form-fields',formFields);$(form).on(events,eventHandler);});}
if(contextIsForm){formFields=fieldsList(context).join(',');var currentFields=$(context).attr('data-drupal-form-fields');if(formFields!==currentFields){triggerFormUpdated(context);}}},detach:function detach(context,settings,trigger){var $context=$(context);var contextIsForm=$context.is('form');if(trigger==='unload'){once.remove('form-updated',contextIsForm?$context:$context.find('form')).forEach(function(form){form.removeAttribute('data-drupal-form-fields');$(form).off('.formUpdated');});}}};Drupal.behaviors.fillUserInfoFromBrowser={attach:function attach(context,settings){var userInfo=['name','mail','homepage'];var $forms=$(once('user-info-from-browser','[data-user-info-from-browser]'));if($forms.length){userInfo.forEach(function(info){var $element=$forms.find("[name=".concat(info,"]"));var browserData=localStorage.getItem("Drupal.visitor.".concat(info));var emptyOrDefault=$element.val()===''||$element.attr('data-drupal-default-value')===$element.val();if($element.length&&emptyOrDefault&&browserData){$element.val(browserData);}});}
$forms.on('submit',function(){userInfo.forEach(function(info){var $element=$forms.find("[name=".concat(info,"]"));if($element.length){localStorage.setItem("Drupal.visitor.".concat(info),$element.val());}});});}};var handleFragmentLinkClickOrHashChange=function handleFragmentLinkClickOrHashChange(e){var url;if(e.type==='click'){url=e.currentTarget.location?e.currentTarget.location:e.currentTarget;}else{url=window.location;}
var hash=url.hash.substr(1);if(hash){var $target=$("#".concat(hash));$('body').trigger('formFragmentLinkClickOrHashChange',[$target]);setTimeout(function(){return $target.trigger('focus');},300);}};var debouncedHandleFragmentLinkClickOrHashChange=debounce(handleFragmentLinkClickOrHashChange,300,true);$(window).on('hashchange.form-fragment',debouncedHandleFragmentLinkClickOrHashChange);$(document).on('click.form-fragment','a[href*="#"]',debouncedHandleFragmentLinkClickOrHashChange);})(jQuery,Drupal,Drupal.debounce);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/form.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.behaviors.js. */
(function($,Drupal){'use strict';var isChrome=(/chrom(e|ium)/.test(window.navigator.userAgent.toLowerCase()));if(isChrome){var backButton=false;if(window.performance){var navEntries=window.performance.getEntriesByType('navigation');if(navEntries.length>0&&navEntries[0].type==='back_forward'){backButton=true;}
else if(window.performance.navigation&&window.performance.navigation.type===window.performance.navigation.TYPE_BACK_FORWARD){backButton=true;}}
if(backButton){var attachBehaviors=Drupal.attachBehaviors;Drupal.attachBehaviors=function(context,settings){setTimeout(function(context,settings){attachBehaviors(context,settings);},300);};}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.behaviors.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/form/form.js. */
!function(e){"function"==typeof define&&define.amd?define(e):e()}((function(){"use strict";(Drupal=>{Drupal.behaviors.form={attach(e){const t=(e.parentNode||e).querySelectorAll(".js-form:not(.js-webform-submit-once)").once("form"),i=(e,t)=>{t.remove(),delete e.dataset.isSubmitting};t.forEach((e=>{e.addEventListener("submit",(t=>{if("isSubmitting"in e.dataset)return!1;let n=t.submitter;n||(n=e.querySelector('[type="submit"]'));let r=document.createElement("div");r.innerHTML=Drupal.theme.ajaxProgressThrobber(Drupal.t("Please wait...")),r=r.firstChild,n.insertAdjacentElement("afterend",r),e.dataset.isSubmitting=!0,window.setTimeout(i.bind(this,e,r),5e3)}))}))}}})(Drupal)}));
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/form/form.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/states.js. */
(function($,Drupal){var states={postponed:[]};Drupal.states=states;function invert(a,invertState){return invertState&&typeof a!=='undefined'?!a:a;}
function _compare2(a,b){if(a===b){return typeof a==='undefined'?a:true;}
return typeof a==='undefined'||typeof b==='undefined';}
function ternary(a,b){if(typeof a==='undefined'){return b;}
if(typeof b==='undefined'){return a;}
return a&&b;}
Drupal.behaviors.states={attach:function attach(context,settings){var $states=$(context).find('[data-drupal-states]');var il=$states.length;var _loop=function _loop(i){var config=JSON.parse($states[i].getAttribute('data-drupal-states'));Object.keys(config||{}).forEach(function(state){new states.Dependent({element:$($states[i]),state:states.State.sanitize(state),constraints:config[state]});});};for(var i=0;i<il;i++){_loop(i);}
while(states.postponed.length){states.postponed.shift()();}}};states.Dependent=function(args){var _this=this;$.extend(this,{values:{},oldValue:null},args);this.dependees=this.getDependees();Object.keys(this.dependees||{}).forEach(function(selector){_this.initializeDependee(selector,_this.dependees[selector]);});};states.Dependent.comparisons={RegExp:function RegExp(reference,value){return reference.test(value);},Function:function Function(reference,value){return reference(value);},Number:function Number(reference,value){return typeof value==='string'?_compare2(reference.toString(),value):_compare2(reference,value);}};states.Dependent.prototype={initializeDependee:function initializeDependee(selector,dependeeStates){var _this2=this;this.values[selector]={};Object.keys(dependeeStates).forEach(function(i){var state=dependeeStates[i];if($.inArray(state,dependeeStates)===-1){return;}
state=states.State.sanitize(state);_this2.values[selector][state.name]=null;$(selector).on("state:".concat(state),{selector:selector,state:state},function(e){_this2.update(e.data.selector,e.data.state,e.value);});new states.Trigger({selector:selector,state:state});});},compare:function compare(reference,selector,state){var value=this.values[selector][state.name];if(reference.constructor.name in states.Dependent.comparisons){return states.Dependent.comparisons[reference.constructor.name](reference,value);}
return _compare2(reference,value);},update:function update(selector,state,value){if(value!==this.values[selector][state.name]){this.values[selector][state.name]=value;this.reevaluate();}},reevaluate:function reevaluate(){var value=this.verifyConstraints(this.constraints);if(value!==this.oldValue){this.oldValue=value;value=invert(value,this.state.invert);this.element.trigger({type:"state:".concat(this.state),value:value,trigger:true});}},verifyConstraints:function verifyConstraints(constraints,selector){var result;if($.isArray(constraints)){var hasXor=$.inArray('xor',constraints)===-1;var len=constraints.length;for(var i=0;i<len;i++){if(constraints[i]!=='xor'){var constraint=this.checkConstraints(constraints[i],selector,i);if(constraint&&(hasXor||result)){return hasXor;}
result=result||constraint;}}}else if($.isPlainObject(constraints)){for(var n in constraints){if(constraints.hasOwnProperty(n)){result=ternary(result,this.checkConstraints(constraints[n],selector,n));if(result===false){return false;}}}}
return result;},checkConstraints:function checkConstraints(value,selector,state){if(typeof state!=='string'||/[0-9]/.test(state[0])){state=null;}else if(typeof selector==='undefined'){selector=state;state=null;}
if(state!==null){state=states.State.sanitize(state);return invert(this.compare(value,selector,state),state.invert);}
return this.verifyConstraints(value,selector);},getDependees:function getDependees(){var cache={};var _compare=this.compare;this.compare=function(reference,selector,state){(cache[selector]||(cache[selector]=[])).push(state.name);};this.verifyConstraints(this.constraints);this.compare=_compare;return cache;}};states.Trigger=function(args){$.extend(this,args);if(this.state in states.Trigger.states){this.element=$(this.selector);if(!this.element.data("trigger:".concat(this.state))){this.initialize();}}};states.Trigger.prototype={initialize:function initialize(){var _this3=this;var trigger=states.Trigger.states[this.state];if(typeof trigger==='function'){trigger.call(window,this.element);}else{Object.keys(trigger||{}).forEach(function(event){_this3.defaultTrigger(event,trigger[event]);});}
this.element.data("trigger:".concat(this.state),true);},defaultTrigger:function defaultTrigger(event,valueFn){var oldValue=valueFn.call(this.element);this.element.on(event,$.proxy(function(e){var value=valueFn.call(this.element,e);if(oldValue!==value){this.element.trigger({type:"state:".concat(this.state),value:value,oldValue:oldValue});oldValue=value;}},this));states.postponed.push($.proxy(function(){this.element.trigger({type:"state:".concat(this.state),value:oldValue,oldValue:null});},this));}};states.Trigger.states={empty:{keyup:function keyup(){return this.val()==='';}},checked:{change:function change(){var checked=false;this.each(function(){checked=$(this).prop('checked');return!checked;});return checked;}},value:{keyup:function keyup(){if(this.length>1){return this.filter(':checked').val()||false;}
return this.val();},change:function change(){if(this.length>1){return this.filter(':checked').val()||false;}
return this.val();}},collapsed:{collapsed:function collapsed(e){return typeof e!=='undefined'&&'value'in e?e.value:!this.is('[open]');}}};states.State=function(state){this.pristine=state;this.name=state;var process=true;do{while(this.name.charAt(0)==='!'){this.name=this.name.substring(1);this.invert=!this.invert;}
if(this.name in states.State.aliases){this.name=states.State.aliases[this.name];}else{process=false;}}while(process);};states.State.sanitize=function(state){if(state instanceof states.State){return state;}
return new states.State(state);};states.State.aliases={enabled:'!disabled',invisible:'!visible',invalid:'!valid',untouched:'!touched',optional:'!required',filled:'!empty',unchecked:'!checked',irrelevant:'!relevant',expanded:'!collapsed',open:'!collapsed',closed:'collapsed',readwrite:'!readonly'};states.State.prototype={invert:false,toString:function toString(){return this.name;}};var $document=$(document);$document.on('state:disabled',function(e){if(e.trigger){$(e.target).prop('disabled',e.value).closest('.js-form-item, .js-form-submit, .js-form-wrapper').toggleClass('form-disabled',e.value).find('select, input, textarea').prop('disabled',e.value);}});$document.on('state:required',function(e){if(e.trigger){if(e.value){var label="label".concat(e.target.id?"[for=".concat(e.target.id,"]"):'');var $label=$(e.target).attr({required:'required','aria-required':'true'}).closest('.js-form-item, .js-form-wrapper').find(label);if(!$label.hasClass('js-form-required').length){$label.addClass('js-form-required form-required');}}else{$(e.target).removeAttr('required aria-required').closest('.js-form-item, .js-form-wrapper').find('label.js-form-required').removeClass('js-form-required form-required');}}});$document.on('state:visible',function(e){if(e.trigger){$(e.target).closest('.js-form-item, .js-form-submit, .js-form-wrapper').toggle(e.value);}});$document.on('state:checked',function(e){if(e.trigger){$(e.target).prop('checked',e.value);}});$document.on('state:collapsed',function(e){if(e.trigger){if($(e.target).is('[open]')===e.value){$(e.target).find('> summary').trigger('click');}}});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/states.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/form/form.states.js. */
!function(e){"function"==typeof define&&define.amd?define(e):e()}((function(){"use strict";jQuery(document).on("state:required",(e=>{if(e.target){const t=e.target.closest(".js-form-item").querySelector(`label[for="${e.target.id}"], legend`),i=e.value;t.classList.toggle("m-form-item__label--is-required",i)}}))}));
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/form/form.states.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.states.js. */
(function($,Drupal){'use strict';Drupal.webform=Drupal.webform||{};Drupal.webform.states=Drupal.webform.states||{};Drupal.webform.states.slideDown=Drupal.webform.states.slideDown||{};Drupal.webform.states.slideDown.duration='slow';Drupal.webform.states.slideUp=Drupal.webform.states.slideUp||{};Drupal.webform.states.slideUp.duration='fast';$.fn.hasData=function(data){return(typeof this.data(data)!=='undefined');};$.fn.isWebform=function(){return $(this).closest('form.webform-submission-form, form[id^="webform"], form[data-is-webform]').length?true:false;};$.fn.isWebformElement=function(){return($(this).isWebform()||$(this).closest('[data-is-webform-element]').length)?true:false;};Drupal.states.Trigger.states.empty.change=function change(){return this.val()==='';};var states=Drupal.states;Drupal.states.Dependent.prototype.compare=function compare(reference,selector,state){var value=this.values[selector][state.name];var name=reference.constructor.name;if(!name){name=$.type(reference);name=name.charAt(0).toUpperCase()+name.slice(1);}
if(name in states.Dependent.comparisons){return states.Dependent.comparisons[name](reference,value);}
if(reference.constructor.name in states.Dependent.comparisons){return states.Dependent.comparisons[reference.constructor.name](reference,value);}
return _compare2(reference,value);};function _compare2(a,b){if(a===b){return typeof a==='undefined'?a:true;}
return typeof a==='undefined'||typeof b==='undefined';}
Drupal.states.Dependent.comparisons.Object=function(reference,value){if('pattern'in reference){return(new RegExp(reference['pattern'])).test(value);}
else if('!pattern'in reference){return!((new RegExp(reference['!pattern'])).test(value));}
else if('less'in reference){return(value!==''&&parseFloat(reference['less'])>parseFloat(value));}
else if('less_equal'in reference){return(value!==''&&parseFloat(reference['less_equal'])>=parseFloat(value));}
else if('greater'in reference){return(value!==''&&parseFloat(reference['greater'])<parseFloat(value));}
else if('greater_equal'in reference){return(value!==''&&parseFloat(reference['greater_equal'])<=parseFloat(value));}
else if('between'in reference||'!between'in reference){if(value===''){return false;}
var between=reference['between']||reference['!between'];var betweenParts=between.split(':');var greater=betweenParts[0];var less=(typeof betweenParts[1]!=='undefined')?betweenParts[1]:null;var isGreaterThan=(greater===null||greater===''||parseFloat(value)>=parseFloat(greater));var isLessThan=(less===null||less===''||parseFloat(value)<=parseFloat(less));var result=(isGreaterThan&&isLessThan);return(reference['!between'])?!result:result;}
else{return reference.indexOf(value)!==false;}};var $document=$(document);$document.on('state:required',function(e){if(e.trigger&&$(e.target).isWebformElement()){var $target=$(e.target);toggleRequired($target.find('input[type="file"]'),e.value);if($target.is('.js-form-type-radios, .js-form-type-webform-radios-other, .js-webform-type-radios, .js-webform-type-webform-radios-other, .js-webform-type-webform-entity-radios, .webform-likert-table')){$target.toggleClass('required',e.value);toggleRequired($target.find('input[type="radio"]'),e.value);}
if($target.is('.js-form-type-checkboxes, .js-form-type-webform-checkboxes-other, .js-webform-type-checkboxes, .js-webform-type-webform-checkboxes-other')){$target.toggleClass('required',e.value);var $checkboxes=$target.find('input[type="checkbox"]');if(e.value){$checkboxes.on('click',statesCheckboxesRequiredEventHandler);checkboxesRequired($target);}
else{$checkboxes.off('click',statesCheckboxesRequiredEventHandler);toggleRequired($checkboxes,false);}}
if($target.is('.js-webform-tableselect')){$target.toggleClass('required',e.value);var isMultiple=$target.is('[multiple]');if(isMultiple){var $tbody=$target.find('tbody');var $checkboxes=$tbody.find('input[type="checkbox"]');copyRequireMessage($target,$checkboxes);if(e.value){$checkboxes.on('click change',statesCheckboxesRequiredEventHandler);checkboxesRequired($tbody);}
else{$checkboxes.off('click change ',statesCheckboxesRequiredEventHandler);toggleRequired($tbody,false);}}
else{var $radios=$target.find('input[type="radio"]');copyRequireMessage($target,$radios);toggleRequired($radios,e.value);}}
if($target.is('.js-form-type-webform-select-other, .js-webform-type-webform-select-other')){var $select=$target.find('select');toggleRequired($select,e.value);copyRequireMessage($target,$select);}
if($target.find('> label:not([for])').length){$target.find('> label').toggleClass('js-form-required form-required',e.value);}
if($target.is('.js-webform-type-radios, .js-webform-type-checkboxes, fieldset')){$target.find('legend span.fieldset-legend:not(.visually-hidden)').toggleClass('js-form-required form-required',e.value);}
if($target.is('fieldset')){$target.removeAttr('required aria-required');}}});$document.on('state:checked',function(e){if(e.trigger){$(e.target).trigger('change');}});$document.on('state:readonly',function(e){if(e.trigger&&$(e.target).isWebformElement()){$(e.target).prop('readonly',e.value).closest('.js-form-item, .js-form-wrapper').toggleClass('webform-readonly',e.value).find('input, textarea').prop('readonly',e.value);$(e.target).trigger('webform:readonly').find('select, input, textarea, button').trigger('webform:readonly');}});$document.on('state:visible state:visible-slide',function(e){if(e.trigger&&$(e.target).isWebformElement()){if(e.value){$(':input',e.target).addBack().each(function(){restoreValueAndRequired(this);triggerEventHandlers(this);});}
else{$(':input',e.target).addBack().each(function(){backupValueAndRequired(this);clearValueAndRequired(this);triggerEventHandlers(this);});}}});$document.on('state:visible-slide',function(e){if(e.trigger&&$(e.target).isWebformElement()){var effect=e.value?'slideDown':'slideUp';var duration=Drupal.webform.states[effect].duration;$(e.target).closest('.js-form-item, .js-form-submit, .js-form-wrapper')[effect](duration);}});Drupal.states.State.aliases['invisible-slide']='!visible-slide';$document.on('state:disabled',function(e){if(e.trigger&&$(e.target).isWebformElement()){$(e.target).prop('disabled',e.value).closest('.js-form-item, .js-form-submit, .js-form-wrapper').toggleClass('form-disabled',e.value).find('select, input, textarea, button').prop('disabled',e.value);var fileElements=$(e.target).find(':input[type="hidden"][name$="[fids]"]');if(fileElements.length){if($(e.target).is('fieldset')){$(e.target).prop('disabled',false);}
fileElements.removeAttr('disabled');}
$(e.target).trigger('webform:disabled').find('select, input, textarea, button').trigger('webform:disabled');}});Drupal.behaviors.webformCheckboxesRequired={attach:function(context){$('.js-form-type-checkboxes.required, .js-form-type-webform-checkboxes-other.required, .js-webform-type-checkboxes.required, .js-webform-type-webform-checkboxes-other.required, .js-webform-type-webform-radios-other.checkboxes',context).once('webform-checkboxes-required').each(function(){var $element=$(this);$element.find('input[type="checkbox"]').on('click',statesCheckboxesRequiredEventHandler);setTimeout(function(){checkboxesRequired($element);});});}};Drupal.behaviors.webformRadiosRequired={attach:function(context){$('.js-form-type-radios, .js-form-type-webform-radios-other, .js-webform-type-radios, .js-webform-type-webform-radios-other, .js-webform-type-webform-entity-radios, .js-webform-type-webform-scale',context).once('webform-radios-required').each(function(){var $element=$(this);setTimeout(function(){radiosRequired($element);});});}};Drupal.behaviors.webformTableSelectRequired={attach:function(context){$('.js-webform-tableselect.required',context).once('webform-tableselect-required').each(function(){var $element=$(this);var $tbody=$element.find('tbody');var isMultiple=$element.is('[multiple]');if(isMultiple){$tbody.find('input[type="checkbox"]').on('click change',function(){checkboxesRequired($tbody);});}
setTimeout(function(){isMultiple?checkboxesRequired($tbody):radiosRequired($element);});});}};function checkboxesRequired($element){var $firstCheckbox=$element.find('input[type="checkbox"]').first();var isChecked=$element.find('input[type="checkbox"]').is(':checked');toggleRequired($firstCheckbox,!isChecked);copyRequireMessage($element,$firstCheckbox);}
function radiosRequired($element){var $radios=$element.find('input[type="radio"]');var isRequired=$element.hasClass('required');toggleRequired($radios,isRequired);copyRequireMessage($element,$radios);}
function statesCheckboxesRequiredEventHandler(){var $element=$(this).closest('.js-webform-type-checkboxes, .js-webform-type-webform-checkboxes-other');checkboxesRequired($element);}
function triggerEventHandlers(input){var $input=$(input);var type=input.type;var tag=input.tagName.toLowerCase();var extraParameters=['webform.states'];if(type==='checkbox'||type==='radio'){$input.trigger('change',extraParameters).trigger('blur',extraParameters);}
else if(tag==='select'){if($input.closest('.webform-type-address').length){if(!$input.data('webform-states-address-initialized')&&$input.attr('autocomplete')==='country'&&$input.val()===$input.find("option[selected]").attr('value')){return;}
$input.data('webform-states-address-initialized',true);}
$input.trigger('change',extraParameters).trigger('blur',extraParameters);}
else if(type!=='submit'&&type!=='button'&&type!=='file'){var hasInputMask=($.fn.inputmask&&$input.hasClass('js-webform-input-mask'));hasInputMask&&$input.inputmask('remove');$input.trigger('input',extraParameters).trigger('change',extraParameters).trigger('keydown',extraParameters).trigger('keyup',extraParameters).trigger('blur',extraParameters);hasInputMask&&$input.inputmask();}}
function backupValueAndRequired(input){var $input=$(input);var type=input.type;var tag=input.tagName.toLowerCase();if($input.prop('required')&&!$input.hasData('webform-required')){$input.data('webform-required',true);}
if(!$input.hasData('webform-value')){if(type==='checkbox'||type==='radio'){$input.data('webform-value',$input.prop('checked'));}
else if(tag==='select'){var values=[];$input.find('option:selected').each(function(i,option){values[i]=option.value;});$input.data('webform-value',values);}
else if(type!=='submit'&&type!=='button'){$input.data('webform-value',input.value);}}}
function restoreValueAndRequired(input){var $input=$(input);var value=$input.data('webform-value');if(typeof value!=='undefined'){var type=input.type;var tag=input.tagName.toLowerCase();if(type==='checkbox'||type==='radio'){$input.prop('checked',value);}
else if(tag==='select'){$.each(value,function(i,option_value){option_value=option_value.replace(/'/g,"\\\'");$input.find("option[value='"+option_value+"']").prop('selected',true);});}
else if(type!=='submit'&&type!=='button'){input.value=value;}
$input.removeData('webform-value');}
var required=$input.data('webform-required');if(typeof required!=='undefined'){if(required){$input.prop('required',true);}
$input.removeData('webform-required');}}
function clearValueAndRequired(input){var $input=$(input);if($input.closest('[data-webform-states-no-clear]').length){return;}
var type=input.type;var tag=input.tagName.toLowerCase();if(type==='checkbox'||type==='radio'){$input.prop('checked',false);}
else if(tag==='select'){if($input.find('option[value=""]').length){$input.val('');}
else{input.selectedIndex=-1;}}
else if(type!=='submit'&&type!=='button'){input.value=(type==='color')?'#000000':'';}
$input.prop('required',false);}
function toggleRequired($input,required){var isCheckboxOrRadio=($input.attr('type')==='radio'||$input.attr('type')==='checkbox');if(required){if(isCheckboxOrRadio){$input.attr({'required':'required'});}
else{$input.attr({'required':'required','aria-required':'true'});}}
else{if(isCheckboxOrRadio){$input.removeAttr('required');}
else{$input.removeAttr('required aria-required');}}}
function copyRequireMessage($source,$destination){if($source.attr('data-msg-required')){$destination.attr('data-msg-required',$source.attr('data-msg-required'));}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.states.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.js. */
(function($,Drupal){'use strict';Drupal.behaviors.webformRemoveFormSingleSubmit={attach:function attach(){function onFormSubmit(e){var $form=$(e.currentTarget);$form.removeAttr('data-drupal-form-submit-last');}
$('body').once('webform-single-submit').on('submit.singleSubmit','form.webform-remove-single-submit',onFormSubmit);}};Drupal.behaviors.webformDisableAutoSubmit={attach:function(context){$('.js-webform-disable-autosubmit input').not(':button, :submit, :reset, :image, :file').once('webform-disable-autosubmit').on('keyup keypress',function(e){if(e.which===13){e.preventDefault();return false;}});}};Drupal.behaviors.webformRequiredError={attach:function(context){$(context).find(':input[data-webform-required-error], :input[data-webform-pattern-error]').once('webform-required-error').on('invalid',function(){this.setCustomValidity('');if(this.valid){return;}
if(this.validity.patternMismatch&&$(this).attr('data-webform-pattern-error')){this.setCustomValidity($(this).attr('data-webform-pattern-error'));}
else if(this.validity.valueMissing&&$(this).attr('data-webform-required-error')){this.setCustomValidity($(this).attr('data-webform-required-error'));}}).on('input change',function(){var name=$(this).attr('name');$(this.form).find(':input[name="'+name+'"]').each(function(){this.setCustomValidity('');});});}};$(document).on('state:required',function(e){$(e.target).filter('[data-webform-required-error]').each(function(){this.setCustomValidity('');});});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.unsaved.js. */
(function($,Drupal){'use strict';var unsaved=false;Drupal.behaviors.webformUnsaved={clear:function(){unsaved=false;},get:function(){return unsaved;},set:function(value){unsaved=value;},attach:function(context){if($('.js-webform-unsaved[data-webform-unsaved]').once('data-webform-unsaved').length){unsaved=true;}
else{$('.js-webform-unsaved :input:not(:button, :submit, :reset, [type="hidden"])').once('webform-unsaved').on('change keypress',function(event,param1){if(param1!=='webform.states'){unsaved=true;}});}
$('.js-webform-unsaved button, .js-webform-unsaved input[type="submit"]',context).once('webform-unsaved').not('[data-webform-unsaved-ignore]').on('click',function(event){if($(this).hasClass('webform-button--reset')&&unsaved){if(!window.confirm(Drupal.t('Changes you made may not be saved.')+'\n\n'+Drupal.t('Press OK to leave this page or Cancel to stay.'))){return false;}}
unsaved=false;});if(typeof Drupal.Ajax!=='undefined'&&typeof Drupal.Ajax.prototype.beforeSubmitWebformUnsavedOriginal==='undefined'){Drupal.Ajax.prototype.beforeSubmitWebformUnsavedOriginal=Drupal.Ajax.prototype.beforeSubmit;Drupal.Ajax.prototype.beforeSubmit=function(form_values,element_settings,options){unsaved=false;return this.beforeSubmitWebformUnsavedOriginal.apply(this,arguments);};}
if(window.CKEDITOR&&!CKEDITOR.webformUnsaved){CKEDITOR.webformUnsaved=true;CKEDITOR.on('instanceCreated',function(event){event.editor.on('change',function(evt){unsaved=true;});});}}};$(window).on('beforeunload',function(){if(unsaved){return true;}});$(function(){var isIOSorOpera=navigator.userAgent.toLowerCase().match(/iphone|ipad|ipod|opera/)||navigator.platform.toLowerCase().match(/iphone|ipad|ipod/)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);if(!isIOSorOpera){return;}
$('a:not(.use-ajax)').bind('click',function(evt){var a=$(evt.target).closest('a');var href=a.attr('href');if(typeof href!=='undefined'&&!(href.match(/^#/)||href.trim()==='')){if($(window).triggerHandler('beforeunload')){if(!window.confirm(Drupal.t('Changes you made may not be saved.')+'\n\n'+Drupal.t('Press OK to leave this page or Cancel to stay.'))){return false;}}
var target=a.attr('target');if(target){window.open(href,target);}
else{window.location.href=href;}
return false;}});});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.unsaved.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/progress.js. */
(function($,Drupal){Drupal.theme.progressBar=function(id){return"<div id=\"".concat(id,"\" class=\"progress\" aria-live=\"polite\">")+'<div class="progress__label">&nbsp;</div>'+'<div class="progress__track"><div class="progress__bar"></div></div>'+'<div class="progress__percentage"></div>'+'<div class="progress__description">&nbsp;</div>'+'</div>';};Drupal.ProgressBar=function(id,updateCallback,method,errorCallback){this.id=id;this.method=method||'GET';this.updateCallback=updateCallback;this.errorCallback=errorCallback;this.element=$(Drupal.theme('progressBar',id));};$.extend(Drupal.ProgressBar.prototype,{setProgress:function setProgress(percentage,message,label){if(percentage>=0&&percentage<=100){$(this.element).find('div.progress__bar').css('width',"".concat(percentage,"%"));$(this.element).find('div.progress__percentage').html("".concat(percentage,"%"));}
$('div.progress__description',this.element).html(message);$('div.progress__label',this.element).html(label);if(this.updateCallback){this.updateCallback(percentage,message,this);}},startMonitoring:function startMonitoring(uri,delay){this.delay=delay;this.uri=uri;this.sendPing();},stopMonitoring:function stopMonitoring(){clearTimeout(this.timer);this.uri=null;},sendPing:function sendPing(){if(this.timer){clearTimeout(this.timer);}
if(this.uri){var pb=this;var uri=this.uri;if(uri.indexOf('?')===-1){uri+='?';}else{uri+='&';}
uri+='_format=json';$.ajax({type:this.method,url:uri,data:'',dataType:'json',success:function success(progress){if(progress.status===0){pb.displayError(progress.data);return;}
pb.setProgress(progress.percentage,progress.message,progress.label);pb.timer=setTimeout(function(){pb.sendPing();},pb.delay);},error:function error(xmlhttp){var e=new Drupal.AjaxError(xmlhttp,pb.uri);pb.displayError("<pre>".concat(e.message,"</pre>"));}});}},displayError:function displayError(string){var error=$('<div class="messages messages--error"></div>').html(string);$(this.element).before(error).hide();if(this.errorCallback){this.errorCallback(this);}}});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/progress.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/modules/responsive_image/js/responsive_image.ajax.js. */
(function(Drupal){Drupal.behaviors.responsiveImageAJAX={attach:function attach(){if(window.picturefill){window.picturefill();}}};})(Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/modules/responsive_image/js/responsive_image.ajax.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/ajax.js. */
function _toConsumableArray(arr){return _arrayWithoutHoles(arr)||_iterableToArray(arr)||_unsupportedIterableToArray(arr)||_nonIterableSpread();}
function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}
function _unsupportedIterableToArray(o,minLen){if(!o)return;if(typeof o==="string")return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);if(n==="Object"&&o.constructor)n=o.constructor.name;if(n==="Map"||n==="Set")return Array.from(o);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen);}
function _iterableToArray(iter){if(typeof Symbol!=="undefined"&&iter[Symbol.iterator]!=null||iter["@@iterator"]!=null)return Array.from(iter);}
function _arrayWithoutHoles(arr){if(Array.isArray(arr))return _arrayLikeToArray(arr);}
function _arrayLikeToArray(arr,len){if(len==null||len>arr.length)len=arr.length;for(var i=0,arr2=new Array(len);i<len;i++){arr2[i]=arr[i];}return arr2;}
(function($,window,Drupal,drupalSettings,_ref){var isFocusable=_ref.isFocusable,tabbable=_ref.tabbable;Drupal.behaviors.AJAX={attach:function attach(context,settings){function loadAjaxBehavior(base){var elementSettings=settings.ajax[base];if(typeof elementSettings.selector==='undefined'){elementSettings.selector="#".concat(base);}
once('drupal-ajax',$(elementSettings.selector)).forEach(function(el){elementSettings.element=el;elementSettings.base=base;Drupal.ajax(elementSettings);});}
Object.keys(settings.ajax||{}).forEach(function(base){return loadAjaxBehavior(base);});Drupal.ajax.bindAjaxLinks(document.body);once('ajax','.use-ajax-submit').forEach(function(el){var elementSettings={};elementSettings.url=$(el.form).attr('action');elementSettings.setClick=true;elementSettings.event='click';elementSettings.progress={type:'throbber'};elementSettings.base=el.id;elementSettings.element=el;Drupal.ajax(elementSettings);});},detach:function detach(context,settings,trigger){if(trigger==='unload'){Drupal.ajax.expired().forEach(function(instance){Drupal.ajax.instances[instance.instanceIndex]=null;});}}};Drupal.AjaxError=function(xmlhttp,uri,customMessage){var statusCode;var statusText;var responseText;if(xmlhttp.status){statusCode="\n".concat(Drupal.t('An AJAX HTTP error occurred.'),"\n").concat(Drupal.t('HTTP Result Code: !status',{'!status':xmlhttp.status}));}else{statusCode="\n".concat(Drupal.t('An AJAX HTTP request terminated abnormally.'));}
statusCode+="\n".concat(Drupal.t('Debugging information follows.'));var pathText="\n".concat(Drupal.t('Path: !uri',{'!uri':uri}));statusText='';try{statusText="\n".concat(Drupal.t('StatusText: !statusText',{'!statusText':xmlhttp.statusText.trim()}));}catch(e){}
responseText='';try{responseText="\n".concat(Drupal.t('ResponseText: !responseText',{'!responseText':xmlhttp.responseText.trim()}));}catch(e){}
responseText=responseText.replace(/<("[^"]*"|'[^']*'|[^'">])*>/gi,'');responseText=responseText.replace(/[\n]+\s+/g,'\n');var readyStateText=xmlhttp.status===0?"\n".concat(Drupal.t('ReadyState: !readyState',{'!readyState':xmlhttp.readyState})):'';customMessage=customMessage?"\n".concat(Drupal.t('CustomMessage: !customMessage',{'!customMessage':customMessage})):'';this.message=statusCode+pathText+statusText+customMessage+responseText+readyStateText;this.name='AjaxError';};Drupal.AjaxError.prototype=new Error();Drupal.AjaxError.prototype.constructor=Drupal.AjaxError;Drupal.ajax=function(settings){if(arguments.length!==1){throw new Error('Drupal.ajax() function must be called with one configuration object only');}
var base=settings.base||false;var element=settings.element||false;delete settings.base;delete settings.element;if(!settings.progress&&!element){settings.progress=false;}
var ajax=new Drupal.Ajax(base,element,settings);ajax.instanceIndex=Drupal.ajax.instances.length;Drupal.ajax.instances.push(ajax);return ajax;};Drupal.ajax.instances=[];Drupal.ajax.expired=function(){return Drupal.ajax.instances.filter(function(instance){return instance&&instance.element!==false&&!document.body.contains(instance.element);});};Drupal.ajax.bindAjaxLinks=function(element){once('ajax','.use-ajax',element).forEach(function(ajaxLink){var $linkElement=$(ajaxLink);var elementSettings={progress:{type:'throbber'},dialogType:$linkElement.data('dialog-type'),dialog:$linkElement.data('dialog-options'),dialogRenderer:$linkElement.data('dialog-renderer'),base:$linkElement.attr('id'),element:ajaxLink};var href=$linkElement.attr('href');if(href){elementSettings.url=href;elementSettings.event='click';}
Drupal.ajax(elementSettings);});};Drupal.Ajax=function(base,element,elementSettings){var defaults={event:element?'mousedown':null,keypress:true,selector:base?"#".concat(base):null,effect:'none',speed:'none',method:'replaceWith',progress:{type:'throbber',message:Drupal.t('Please wait...')},submit:{js:true}};$.extend(this,defaults,elementSettings);this.commands=new Drupal.AjaxCommands();this.instanceIndex=false;if(this.wrapper){this.wrapper="#".concat(this.wrapper);}
this.element=element;this.element_settings=elementSettings;this.elementSettings=elementSettings;if(this.element&&this.element.form){this.$form=$(this.element.form);}
if(!this.url){var $element=$(this.element);if($element.is('a')){this.url=$element.attr('href');}else if(this.element&&element.form){this.url=this.$form.attr('action');}}
var originalUrl=this.url;this.url=this.url.replace(/\/nojs(\/|$|\?|#)/,'/ajax$1');if(drupalSettings.ajaxTrustedUrl[originalUrl]){drupalSettings.ajaxTrustedUrl[this.url]=true;}
var ajax=this;ajax.options={url:ajax.url,data:ajax.submit,beforeSerialize:function beforeSerialize(elementSettings,options){return ajax.beforeSerialize(elementSettings,options);},beforeSubmit:function beforeSubmit(formValues,elementSettings,options){ajax.ajaxing=true;return ajax.beforeSubmit(formValues,elementSettings,options);},beforeSend:function beforeSend(xmlhttprequest,options){ajax.ajaxing=true;return ajax.beforeSend(xmlhttprequest,options);},success:function success(response,status,xmlhttprequest){if(typeof response==='string'){response=$.parseJSON(response);}
if(response!==null&&!drupalSettings.ajaxTrustedUrl[ajax.url]){if(xmlhttprequest.getResponseHeader('X-Drupal-Ajax-Token')!=='1'){var customMessage=Drupal.t('The response failed verification so will not be processed.');return ajax.error(xmlhttprequest,ajax.url,customMessage);}}
return ajax.success(response,status);},complete:function complete(xmlhttprequest,status){ajax.ajaxing=false;if(status==='error'||status==='parsererror'){return ajax.error(xmlhttprequest,ajax.url);}},dataType:'json',jsonp:false,type:'POST'};if(elementSettings.dialog){ajax.options.data.dialogOptions=elementSettings.dialog;}
if(ajax.options.url.indexOf('?')===-1){ajax.options.url+='?';}else{ajax.options.url+='&';}
var wrapper="drupal_".concat(elementSettings.dialogType||'ajax');if(elementSettings.dialogRenderer){wrapper+=".".concat(elementSettings.dialogRenderer);}
ajax.options.url+="".concat(Drupal.ajax.WRAPPER_FORMAT,"=").concat(wrapper);$(ajax.element).on(elementSettings.event,function(event){if(!drupalSettings.ajaxTrustedUrl[ajax.url]&&!Drupal.url.isLocal(ajax.url)){throw new Error(Drupal.t('The callback URL is not local and not trusted: !url',{'!url':ajax.url}));}
return ajax.eventResponse(this,event);});if(elementSettings.keypress){$(ajax.element).on('keypress',function(event){return ajax.keypressResponse(this,event);});}
if(elementSettings.prevent){$(ajax.element).on(elementSettings.prevent,false);}};Drupal.ajax.WRAPPER_FORMAT='_wrapper_format';Drupal.Ajax.AJAX_REQUEST_PARAMETER='_drupal_ajax';Drupal.Ajax.prototype.execute=function(){if(this.ajaxing){return;}
try{this.beforeSerialize(this.element,this.options);return $.ajax(this.options);}catch(e){this.ajaxing=false;window.alert("An error occurred while attempting to process ".concat(this.options.url,": ").concat(e.message));return $.Deferred().reject();}};Drupal.Ajax.prototype.keypressResponse=function(element,event){var ajax=this;if(event.which===13||event.which===32&&element.type!=='text'&&element.type!=='textarea'&&element.type!=='tel'&&element.type!=='number'){event.preventDefault();event.stopPropagation();$(element).trigger(ajax.elementSettings.event);}};Drupal.Ajax.prototype.eventResponse=function(element,event){event.preventDefault();event.stopPropagation();var ajax=this;if(ajax.ajaxing){return;}
try{if(ajax.$form){if(ajax.setClick){element.form.clk=element;}
ajax.$form.ajaxSubmit(ajax.options);}else{ajax.beforeSerialize(ajax.element,ajax.options);$.ajax(ajax.options);}}catch(e){ajax.ajaxing=false;window.alert("An error occurred while attempting to process ".concat(ajax.options.url,": ").concat(e.message));}};Drupal.Ajax.prototype.beforeSerialize=function(element,options){if(this.$form&&document.body.contains(this.$form.get(0))){var settings=this.settings||drupalSettings;Drupal.detachBehaviors(this.$form.get(0),settings,'serialize');}
options.data[Drupal.Ajax.AJAX_REQUEST_PARAMETER]=1;var pageState=drupalSettings.ajaxPageState;options.data['ajax_page_state[theme]']=pageState.theme;options.data['ajax_page_state[theme_token]']=pageState.theme_token;options.data['ajax_page_state[libraries]']=pageState.libraries;};Drupal.Ajax.prototype.beforeSubmit=function(formValues,element,options){};Drupal.Ajax.prototype.beforeSend=function(xmlhttprequest,options){if(this.$form){options.extraData=options.extraData||{};options.extraData.ajax_iframe_upload='1';var v=$.fieldValue(this.element);if(v!==null){options.extraData[this.element.name]=v;}}
$(this.element).prop('disabled',true);if(!this.progress||!this.progress.type){return;}
var progressIndicatorMethod="setProgressIndicator".concat(this.progress.type.slice(0,1).toUpperCase()).concat(this.progress.type.slice(1).toLowerCase());if(progressIndicatorMethod in this&&typeof this[progressIndicatorMethod]==='function'){this[progressIndicatorMethod].call(this);}};Drupal.theme.ajaxProgressThrobber=function(message){var messageMarkup=typeof message==='string'?Drupal.theme('ajaxProgressMessage',message):'';var throbber='<div class="throbber">&nbsp;</div>';return"<div class=\"ajax-progress ajax-progress-throbber\">".concat(throbber).concat(messageMarkup,"</div>");};Drupal.theme.ajaxProgressIndicatorFullscreen=function(){return'<div class="ajax-progress ajax-progress-fullscreen">&nbsp;</div>';};Drupal.theme.ajaxProgressMessage=function(message){return"<div class=\"message\">".concat(message,"</div>");};Drupal.theme.ajaxProgressBar=function($element){return $('<div class="ajax-progress ajax-progress-bar"></div>').append($element);};Drupal.Ajax.prototype.setProgressIndicatorBar=function(){var progressBar=new Drupal.ProgressBar("ajax-progress-".concat(this.element.id),$.noop,this.progress.method,$.noop);if(this.progress.message){progressBar.setProgress(-1,this.progress.message);}
if(this.progress.url){progressBar.startMonitoring(this.progress.url,this.progress.interval||1500);}
this.progress.element=$(Drupal.theme('ajaxProgressBar',progressBar.element));this.progress.object=progressBar;$(this.element).after(this.progress.element);};Drupal.Ajax.prototype.setProgressIndicatorThrobber=function(){this.progress.element=$(Drupal.theme('ajaxProgressThrobber',this.progress.message));$(this.element).after(this.progress.element);};Drupal.Ajax.prototype.setProgressIndicatorFullscreen=function(){this.progress.element=$(Drupal.theme('ajaxProgressIndicatorFullscreen'));$('body').append(this.progress.element);};Drupal.Ajax.prototype.success=function(response,status){var _this=this;if(this.progress.element){$(this.progress.element).remove();}
if(this.progress.object){this.progress.object.stopMonitoring();}
$(this.element).prop('disabled',false);var elementParents=$(this.element).parents('[data-drupal-selector]').addBack().toArray();var focusChanged=false;Object.keys(response||{}).forEach(function(i){if(response[i].command&&_this.commands[response[i].command]){_this.commands[response[i].command](_this,response[i],status);if(response[i].command==='invoke'&&response[i].method==='focus'||response[i].command==='focusFirst'){focusChanged=true;}}});if(!focusChanged&&this.element&&!$(this.element).data('disable-refocus')){var target=false;for(var n=elementParents.length-1;!target&&n>=0;n--){target=document.querySelector("[data-drupal-selector=\"".concat(elementParents[n].getAttribute('data-drupal-selector'),"\"]"));}
if(target){$(target).trigger('focus');}}
if(this.$form&&document.body.contains(this.$form.get(0))){var settings=this.settings||drupalSettings;Drupal.attachBehaviors(this.$form.get(0),settings);}
this.settings=null;};Drupal.Ajax.prototype.getEffect=function(response){var type=response.effect||this.effect;var speed=response.speed||this.speed;var effect={};if(type==='none'){effect.showEffect='show';effect.hideEffect='hide';effect.showSpeed='';}else if(type==='fade'){effect.showEffect='fadeIn';effect.hideEffect='fadeOut';effect.showSpeed=speed;}else{effect.showEffect="".concat(type,"Toggle");effect.hideEffect="".concat(type,"Toggle");effect.showSpeed=speed;}
return effect;};Drupal.Ajax.prototype.error=function(xmlhttprequest,uri,customMessage){if(this.progress.element){$(this.progress.element).remove();}
if(this.progress.object){this.progress.object.stopMonitoring();}
$(this.wrapper).show();$(this.element).prop('disabled',false);if(this.$form&&document.body.contains(this.$form.get(0))){var settings=this.settings||drupalSettings;Drupal.attachBehaviors(this.$form.get(0),settings);}
throw new Drupal.AjaxError(xmlhttprequest,uri,customMessage);};Drupal.theme.ajaxWrapperNewContent=function($newContent,ajax,response){return(response.effect||ajax.effect)!=='none'&&$newContent.filter(function(i){return!($newContent[i].nodeName==='#comment'||$newContent[i].nodeName==='#text'&&/^(\s|\n|\r)*$/.test($newContent[i].textContent));}).length>1?Drupal.theme('ajaxWrapperMultipleRootElements',$newContent):$newContent;};Drupal.theme.ajaxWrapperMultipleRootElements=function($elements){return $('<div></div>').append($elements);};Drupal.AjaxCommands=function(){};Drupal.AjaxCommands.prototype={insert:function insert(ajax,response){var $wrapper=response.selector?$(response.selector):$(ajax.wrapper);var method=response.method||ajax.method;var effect=ajax.getEffect(response);var settings=response.settings||ajax.settings||drupalSettings;var $newContent=$($.parseHTML(response.data,document,true));$newContent=Drupal.theme('ajaxWrapperNewContent',$newContent,ajax,response);switch(method){case'html':case'replaceWith':case'replaceAll':case'empty':case'remove':Drupal.detachBehaviors($wrapper.get(0),settings);break;default:break;}
$wrapper[method]($newContent);if(effect.showEffect!=='show'){$newContent.hide();}
var $ajaxNewContent=$newContent.find('.ajax-new-content');if($ajaxNewContent.length){$ajaxNewContent.hide();$newContent.show();$ajaxNewContent[effect.showEffect](effect.showSpeed);}else if(effect.showEffect!=='show'){$newContent[effect.showEffect](effect.showSpeed);}
if($newContent.parents('html').length){$newContent.each(function(index,element){if(element.nodeType===Node.ELEMENT_NODE){Drupal.attachBehaviors(element,settings);}});}},remove:function remove(ajax,response,status){var settings=response.settings||ajax.settings||drupalSettings;$(response.selector).each(function(){Drupal.detachBehaviors(this,settings);}).remove();},changed:function changed(ajax,response,status){var $element=$(response.selector);if(!$element.hasClass('ajax-changed')){$element.addClass('ajax-changed');if(response.asterisk){$element.find(response.asterisk).append(" <abbr class=\"ajax-changed\" title=\"".concat(Drupal.t('Changed'),"\">*</abbr> "));}}},alert:function alert(ajax,response,status){window.alert(response.text);},announce:function announce(ajax,response){if(response.priority){Drupal.announce(response.text,response.priority);}else{Drupal.announce(response.text);}},redirect:function redirect(ajax,response,status){window.location=response.url;},css:function css(ajax,response,status){$(response.selector).css(response.argument);},settings:function settings(ajax,response,status){var ajaxSettings=drupalSettings.ajax;if(ajaxSettings){Drupal.ajax.expired().forEach(function(instance){if(instance.selector){var selector=instance.selector.replace('#','');if(selector in ajaxSettings){delete ajaxSettings[selector];}}});}
if(response.merge){$.extend(true,drupalSettings,response.settings);}else{ajax.settings=response.settings;}},data:function data(ajax,response,status){$(response.selector).data(response.name,response.value);},focusFirst:function focusFirst(ajax,response,status){var focusChanged=false;var container=document.querySelector(response.selector);if(container){var tabbableElements=tabbable(container);if(tabbableElements.length){tabbableElements[0].focus();focusChanged=true;}else if(isFocusable(container)){container.focus();focusChanged=true;}}
if(ajax.hasOwnProperty('element')&&!focusChanged){ajax.element.focus();}},invoke:function invoke(ajax,response,status){var $element=$(response.selector);$element[response.method].apply($element,_toConsumableArray(response.args));},restripe:function restripe(ajax,response,status){$(response.selector).find('> tbody > tr:visible, > tr:visible').removeClass('odd even').filter(':even').addClass('odd').end().filter(':odd').addClass('even');},update_build_id:function update_build_id(ajax,response,status){$("input[name=\"form_build_id\"][value=\"".concat(response.old,"\"]")).val(response.new);},add_css:function add_css(ajax,response,status){$('head').prepend(response.data);},message:function message(ajax,response){var messages=new Drupal.Message(document.querySelector(response.messageWrapperQuerySelector));if(response.clearPrevious){messages.clear();}
messages.add(response.message,response.messageOptions);}};})(jQuery,window,Drupal,drupalSettings,window.tabbable);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/ajax.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.submit_once.js. */
(function($,Drupal){'use strict';Drupal.behaviors.webformSubmitOnce={clear:function(){var $form=$('.js-webform-submit-once');$form.removeData('webform-submitted');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').removeClass('is-disabled');$form.find('.form-actions .ajax-progress.ajax-progress-throbber').remove();},attach:function(context){$('.js-webform-submit-once',context).once('webform-submit-once').each(function(){var $form=$(this);$form.removeData('webform-submitted');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').removeClass('js-webform-submit-clicked');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').on('click',function(){$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').removeClass('js-webform-submit-clicked');$(this).addClass('js-webform-submit-clicked');});$(this).on('submit',function(){var $clickedButton=$form.find('.js-webform-wizard-pages-links :submit.js-webform-submit-clicked, .form-actions :submit.js-webform-submit-clicked');if(!$clickedButton.attr('formnovalidate')&&$.isFunction(jQuery.fn.valid)&&!($form.valid())){return false;}
if($form.data('webform-submitted')){return false;}
$form.data('webform-submitted','true');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').addClass('is-disabled');$clickedButton.after(Drupal.theme.ajaxProgressThrobber());});});}};})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.submit_once.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.element.message.js. */
(function($,Drupal){'use strict';var hasLocalStorage=(function(){try{localStorage.setItem('webform','webform');localStorage.removeItem('webform');return true;}
catch(e){return false;}}());var hasSessionStorage=(function(){try{sessionStorage.setItem('webform','webform');sessionStorage.removeItem('webform');return true;}
catch(e){return false;}}());Drupal.behaviors.webformMessageClose={attach:function(context){$(context).find('.js-webform-message--close').once('webform-message--close').each(function(){var $element=$(this);var id=$element.attr('data-message-id');var storage=$element.attr('data-message-storage');var effect=$element.attr('data-message-close-effect')||'hide';switch(effect){case'slide':effect='slideUp';break;case'fade':effect='fadeOut';break;}
if(isClosed($element,storage,id)){return;}
if($element.attr('style')!=='display: none;'){$element.show();}
$element.find('.js-webform-message__link').on('click',function(event){$element[effect]();setClosed($element,storage,id);$element.trigger('close');event.preventDefault();});});}};function isClosed($element,storage,id){if(!id||!storage){return false;}
switch(storage){case'local':if(hasLocalStorage){return localStorage.getItem('Drupal.webform.message.'+id)||false;}
return false;case'session':if(hasSessionStorage){return sessionStorage.getItem('Drupal.webform.message.'+id)||false;}
return false;default:return false;}}
function setClosed($element,storage,id){if(!id||!storage){return;}
switch(storage){case'local':if(hasLocalStorage){localStorage.setItem('Drupal.webform.message.'+id,true);}
break;case'session':if(hasSessionStorage){sessionStorage.setItem('Drupal.webform.message.'+id,true);}
break;case'user':case'state':case'custom':$.get($element.find('.js-webform-message__link').attr('href'));return true;}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.element.message.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/antibot/js/antibot.js. */
(function(Drupal,drupalSettings){"use strict";Drupal.antibot={};Drupal.behaviors.antibot={attach:function(context){drupalSettings.antibot.human=false;document.body.addEventListener('mousemove',function(){Drupal.antibot.unlockForms();});document.body.addEventListener('touchmove',function(){Drupal.antibot.unlockForms();});document.body.addEventListener('keydown',function(e){if((e.code=='Tab')||(e.code=='Enter')){Drupal.antibot.unlockForms();}});}};Drupal.antibot.unlockForms=function(){if(!drupalSettings.antibot.human){if(drupalSettings.antibot.forms!=undefined){Object.values(drupalSettings.antibot.forms).forEach(function(config){const form=document.getElementById(config.id);if(form){form.setAttribute('action',form.getAttribute('data-action'));const input=form.querySelector('input[name="antibot_key"]');if(input){input.value=config.key;}}});}
drupalSettings.antibot.human=true;}};})(Drupal,drupalSettings);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/antibot/js/antibot.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/libraries/collapse/collapse.js. */
!function(e,s){"object"==typeof exports&&"undefined"!=typeof module?module.exports=s():"function"==typeof define&&define.amd?define(s):(e="undefined"!=typeof globalThis?globalThis:e||self).Collapse=s()}(this,(function(){"use strict";class Collapse{static defaultOptions={openClass:"is-open",$handlers:null};constructor(e,s){"string"==typeof e&&(e=document.querySelector(e)),this.$el=e,this.$el.collapse=this,this._events=[],this.options={...Collapse.defaultOptions,...s},this.isOpen=!1,this.$handlers=[];let{$handlers:t}=this.options;"string"==typeof t&&(t=document.querySelectorAll(this.options.$handlers)),!1===Array.isArray(t)&&(t=t?[t]:[]),Array.from(document.querySelectorAll("[data-collapse-handler]")).forEach((e=>{Array.from(document.querySelectorAll(e.dataset.collapseHandler)).filter((e=>e===this.$el)).length>0&&t.push(e)})),t.forEach((e=>{this.addHandler(e)}))}deconstructor(){this.$handlers.forEach((e=>{this.removeHandler(e)})),delete this.$el.collapse,this.$el=null,this.options=null,this._events=null,this.handlers=null}on(e,s,t){this._events.find((l=>l.$el===e&&l.type===s&&l.callback===t))&&this.off(e,s,t),this._events.push({$el:e,type:s,callback:t}),e.addEventListener(s,t)}off(e,s,t=null){this._events.filter((l=>l.$el===e&&l.type===s&&(!t||l.callback===t))).forEach((t=>{const l=this._events.indexOf(t);e.removeEventListener(s,t.callback),this._events.splice(l,1)}))}handleToggle(e){this.toggle(),e.preventDefault()}addHandler(e){this.on(e,"click",this.handleToggle.bind(this)),this.$handlers.push(e)}removeHandler(e){const s=this.$handlers.indexOf(e);-1!==s&&(this.off(e,"click"),this.$handlers.splice(s,1))}toggle(){this.isOpen?this.close():this.open()}open(){this.$handlers.forEach((e=>{e.setAttribute("aria-expanded","true")})),this.options.openClass&&this.$el.classList.add(this.options.openClass),this.isOpen=!0;const e=new CustomEvent("open.collapse");this.$el.dispatchEvent(e)}close(){this.$handlers.forEach((e=>{e.setAttribute("aria-expanded","false")})),this.options.openClass&&this.$el.classList.remove(this.options.openClass),this.isOpen=!1;const e=new CustomEvent("close.collapse");this.$el.dispatchEvent(e)}}return Collapse}));
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/libraries/collapse/collapse.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/collapse/collapse.js. */
!function(e){"function"==typeof define&&define.amd?define(e):e()}((function(){"use strict";((Drupal,e)=>{Drupal.Collapse=class DrupalCollapse extends e{constructor(e,s){super(e,s),this.on(this.$el,"transitionend",(e=>{e.target===this.$el&&"height"===e.propertyName&&(this.$el.classList.remove("m-collapse--is-animating"),this.$el.style.removeProperty("height"),e.stopPropagation())}))}open(){super.open(),this.$el.style.height=`${this.$el.scrollHeight}px`,this.$el.classList.add("m-collapse--is-open"),this.$el.classList.add("m-collapse--is-animating")}close(){super.close(),this.$el.style.height=`${this.$el.scrollHeight}px`,this.$el.classList.add("m-collapse--is-animating"),this.$el.classList.remove("m-collapse--is-open"),window.setTimeout((()=>{this.$el.style.removeProperty("height")}),1)}},Drupal.behaviors.collapse={attach(e){(e.parentNode||e).querySelectorAll(".js-collapse").once("collapse").forEach((e=>{new Drupal.Collapse(e)}))}}})(Drupal,Collapse)}));
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/patterns/molecules/collapse/collapse.js. */;
