// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.24/esri/copyright.txt for details.//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/Accessor ../core/Collection ../core/HandleOwner ../core/handleUtils ../core/has ../core/Logger ../core/maybe ../core/reactiveUtils ../core/accessorSupport/decorators/property ../core/arrayUtils ../core/accessorSupport/ensureType ../core/accessorSupport/decorators/subclass ./3d/support/TextureCollection ./input/InputManager ./input/ViewEvents ./interactive/interactiveToolUtils ./interactive/interfaces ./interactive/ToolViewManagerManipulatorState".split(" "),
function(p,g,t,q,e,u,D,v,d,m,h,E,F,w,x,y,z,n,A,B){const C=v.getLogger("esri.views.ToolViewManager");e=function(r){function l(a){var b=r.call(this,a)||this;b._manipulatorState=new B;b.tools=new q;b.cursor=null;b._forEachTool=c=>{for(const k of b.tools.items)if(c(k))break};return b}p._inheritsLoose(l,r);var f=l.prototype;f.initialize=function(){this.handles.add([this.view.on(z.eventTypes,a=>{this._handleInputEvent(a)},y.ViewEventPriorities.TOOL),...n.getToolCollectionHandles(this.tools),this.tools.on("before-remove",
({item:a})=>{this._manipulatorState.clearPointers(a,this._forEachTool)}),this.tools.on("change",()=>{this._refreshToolWatchers()})])};f.destroy=function(){this.detach();this.handles.removeAll()};f.attach=function(){"3d"===this.view.type?(this._set("textures",new x.TextureCollection(this.view._stage,this.view.resourceController.scheduler)),this.handles.add([m.watch(()=>{const {state:a}=this.view;return"camera"in a&&a.camera},()=>{this._forEachManipulator(a=>{if(null!=a.onViewChange)a.onViewChange()})}),
this.view.elevationProvider.on("elevation-change",a=>{this._forEachManipulator(b=>{if(null!=b.onElevationChange)b.onElevationChange(a)})}),u.makeHandle(()=>this._set("textures",d.destroyMaybe(this.textures)))],"attached")):this.handles.add(m.watch(()=>this.view.extent,()=>{this._forEachManipulator(a=>{if(null!=a.onViewChange)a.onViewChange()})}))};f.detach=function(){d.isSome(this.activeTool)&&(this.activeTool=null);this.tools.removeAll();this.handles.remove("attached")};f._forEachManipulator=function(a){this._forEachTool(b=>
{b.manipulators&&b.manipulators.forEach(({manipulator:c})=>a(c,b))})};f._handleInputEvent=function(a){let b=!1;const c={...a,stopPropagation:()=>{b=!0;a.stopPropagation()}};d.isSome(this.activeTool)?this.activeTool.handleInputEvent&&this.activeTool.handleInputEvent(c):this._forEachTool(k=>{!b&&k.visible&&k.handleInputEvent(c)});!b&&"key-down"===a.type&&"Escape"===a.key&&this.activeTool&&(a.stopPropagation(),this.activeTool=null);this._manipulatorState.handleInputEvent(c,{forEachTool:this._forEachTool,
activeTool:this.activeTool,setActiveTool:k=>{this.activeTool=k},view:this.view});!b&&d.isSome(this.activeTool)&&this.activeTool.handleInputEventAfter(c);this._manipulatorState.handleHoverEvent(c,this._forEachTool);this._updateCursor()};f._refreshToolWatchers=function(){this.handles.remove("tools");this._forEachTool(a=>{if(a instanceof t){const b=m.watch(()=>[a.cursor,a.visible,a.editable],()=>{n.areToolManipulatorsEditable(a)||this._manipulatorState.clearPointers(a,this._forEachTool);this._updateCursor()});
this.handles.add(b,"tools")}a.manipulators&&this.handles.add(a.manipulators.on("change",b=>{b.removed.forEach(({id:c})=>{this._manipulatorState.clearPointers(a,this._forEachTool,!0,c)});this._manipulatorState.updateHoveredStateFromKnownPointers(this._forEachTool);this._updateCursor()}),"tools")});this._manipulatorState.updateHoveredStateFromKnownPointers(this._forEachTool);this._updateCursor()};f._updateCursor=function(){const a=this._manipulatorState.cursor;let b=a;this._forEachTool(c=>d.isSome(c.cursor)&&
c.visible&&(d.isNone(a)||!c.preferManipulatorCursor)?(b=c.cursor,!0):!1);this._get("cursor")!==b&&this._set("cursor",b)};f._removeIncompleteTools=function(a){this.tools.filter(b=>(d.isNone(a)||b!==a)&&!b.created&&b.removeIncompleteOnCancel).forEach(b=>{this.tools.remove(b)})};p._createClass(l,[{key:"activeTool",set:function(a){if(d.isSome(a)&&!this.view.ready)C.error("Cannot set active tool while view is not ready.");else if(a!==this.activeTool){var b=this.activeTool;this._set("activeTool",a);d.isSome(b)&&
b.deactivate();d.isSome(a)&&a.activate();this._removeIncompleteTools(a);a=d.isNone(this.activeTool);for(const c of this.tools)c.setEditableFlag(A.EditableFlag.MANAGER,a||c===this.activeTool),b=n.areToolManipulatorsEditable(c),!a&&b||this._manipulatorState.clearPointers(c,this._forEachTool,!b);this._updateCursor()}}},{key:"updating",get:function(){var a,b;return this.updatingHandles.updating||this.tools.some(c=>c.updating)||(null!=(a=null==(b=this.textures)?void 0:b.updating)?a:!1)}}]);return l}(e.HandleOwner);
g.__decorate([h.property({constructOnly:!0,nonNullable:!0})],e.prototype,"view",void 0);g.__decorate([h.property({readOnly:!0,nonNullable:!0})],e.prototype,"textures",void 0);g.__decorate([h.property({value:null})],e.prototype,"activeTool",null);g.__decorate([h.property({readOnly:!0,type:q})],e.prototype,"tools",void 0);g.__decorate([h.property({readOnly:!0})],e.prototype,"cursor",void 0);g.__decorate([h.property({readOnly:!0})],e.prototype,"updating",null);return e=g.__decorate([w.subclass("esri.views.ToolViewManager")],
e)});