/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.js. */
(function($,Drupal){'use strict';Drupal.behaviors.webformRemoveFormSingleSubmit={attach:function attach(){function onFormSubmit(e){var $form=$(e.currentTarget);$form.removeAttr('data-drupal-form-submit-last');}
$('body').once('webform-single-submit').on('submit.singleSubmit','form.webform-remove-single-submit',onFormSubmit);}};Drupal.behaviors.webformDisableAutoSubmit={attach:function(context){$('.js-webform-disable-autosubmit input').not(':button, :submit, :reset, :image, :file').once('webform-disable-autosubmit').on('keyup keypress',function(e){if(e.which===13){e.preventDefault();return false;}});}};Drupal.behaviors.webformRequiredError={attach:function(context){$(context).find(':input[data-webform-required-error], :input[data-webform-pattern-error]').once('webform-required-error').on('invalid',function(){this.setCustomValidity('');if(this.valid){return;}
if(this.validity.patternMismatch&&$(this).attr('data-webform-pattern-error')){this.setCustomValidity($(this).attr('data-webform-pattern-error'));}
else if(this.validity.valueMissing&&$(this).attr('data-webform-required-error')){this.setCustomValidity($(this).attr('data-webform-required-error'));}}).on('input change',function(){var name=$(this).attr('name');$(this.form).find(':input[name="'+name+'"]').each(function(){this.setCustomValidity('');});});}};$(document).on('state:required',function(e){$(e.target).filter('[data-webform-required-error]').each(function(){this.setCustomValidity('');});});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.unsaved.js. */
(function($,Drupal){'use strict';var unsaved=false;Drupal.behaviors.webformUnsaved={clear:function(){unsaved=false;},get:function(){return unsaved;},set:function(value){unsaved=value;},attach:function(context){if($('.js-webform-unsaved[data-webform-unsaved]').once('data-webform-unsaved').length){unsaved=true;}
else{$('.js-webform-unsaved :input:not(:button, :submit, :reset, [type="hidden"])').once('webform-unsaved').on('change keypress',function(event,param1){if(param1!=='webform.states'){unsaved=true;}});}
$('.js-webform-unsaved button, .js-webform-unsaved input[type="submit"]',context).once('webform-unsaved').not('[data-webform-unsaved-ignore]').on('click',function(event){if($(this).hasClass('webform-button--reset')&&unsaved){if(!window.confirm(Drupal.t('Changes you made may not be saved.')+'\n\n'+Drupal.t('Press OK to leave this page or Cancel to stay.'))){return false;}}
unsaved=false;});if(typeof Drupal.Ajax!=='undefined'&&typeof Drupal.Ajax.prototype.beforeSubmitWebformUnsavedOriginal==='undefined'){Drupal.Ajax.prototype.beforeSubmitWebformUnsavedOriginal=Drupal.Ajax.prototype.beforeSubmit;Drupal.Ajax.prototype.beforeSubmit=function(form_values,element_settings,options){unsaved=false;return this.beforeSubmitWebformUnsavedOriginal.apply(this,arguments);};}
if(window.CKEDITOR&&!CKEDITOR.webformUnsaved){CKEDITOR.webformUnsaved=true;CKEDITOR.on('instanceCreated',function(event){event.editor.on('change',function(evt){unsaved=true;});});}}};$(window).on('beforeunload',function(){if(unsaved){return true;}});$(function(){var isIOSorOpera=navigator.userAgent.toLowerCase().match(/iphone|ipad|ipod|opera/)||navigator.platform.toLowerCase().match(/iphone|ipad|ipod/)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);if(!isIOSorOpera){return;}
$('a:not(.use-ajax)').bind('click',function(evt){var a=$(evt.target).closest('a');var href=a.attr('href');if(typeof href!=='undefined'&&!(href.match(/^#/)||href.trim()==='')){if($(window).triggerHandler('beforeunload')){if(!window.confirm(Drupal.t('Changes you made may not be saved.')+'\n\n'+Drupal.t('Press OK to leave this page or Cancel to stay.'))){return false;}}
var target=a.attr('target');if(target){window.open(href,target);}
else{window.location.href=href;}
return false;}});});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.unsaved.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/progress.js. */
(function($,Drupal){Drupal.theme.progressBar=function(id){return"<div id=\"".concat(id,"\" class=\"progress\" aria-live=\"polite\">")+'<div class="progress__label">&nbsp;</div>'+'<div class="progress__track"><div class="progress__bar"></div></div>'+'<div class="progress__percentage"></div>'+'<div class="progress__description">&nbsp;</div>'+'</div>';};Drupal.ProgressBar=function(id,updateCallback,method,errorCallback){this.id=id;this.method=method||'GET';this.updateCallback=updateCallback;this.errorCallback=errorCallback;this.element=$(Drupal.theme('progressBar',id));};$.extend(Drupal.ProgressBar.prototype,{setProgress:function setProgress(percentage,message,label){if(percentage>=0&&percentage<=100){$(this.element).find('div.progress__bar').css('width',"".concat(percentage,"%"));$(this.element).find('div.progress__percentage').html("".concat(percentage,"%"));}
$('div.progress__description',this.element).html(message);$('div.progress__label',this.element).html(label);if(this.updateCallback){this.updateCallback(percentage,message,this);}},startMonitoring:function startMonitoring(uri,delay){this.delay=delay;this.uri=uri;this.sendPing();},stopMonitoring:function stopMonitoring(){clearTimeout(this.timer);this.uri=null;},sendPing:function sendPing(){if(this.timer){clearTimeout(this.timer);}
if(this.uri){var pb=this;var uri=this.uri;if(uri.indexOf('?')===-1){uri+='?';}else{uri+='&';}
uri+='_format=json';$.ajax({type:this.method,url:uri,data:'',dataType:'json',success:function success(progress){if(progress.status===0){pb.displayError(progress.data);return;}
pb.setProgress(progress.percentage,progress.message,progress.label);pb.timer=setTimeout(function(){pb.sendPing();},pb.delay);},error:function error(xmlhttp){var e=new Drupal.AjaxError(xmlhttp,pb.uri);pb.displayError("<pre>".concat(e.message,"</pre>"));}});}},displayError:function displayError(string){var error=$('<div class="messages messages--error"></div>').html(string);$(this.element).before(error).hide();if(this.errorCallback){this.errorCallback(this);}}});})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/progress.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/modules/responsive_image/js/responsive_image.ajax.js. */
(function(Drupal){Drupal.behaviors.responsiveImageAJAX={attach:function attach(){if(window.picturefill){window.picturefill();}}};})(Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/modules/responsive_image/js/responsive_image.ajax.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/core/misc/ajax.js. */
function _toConsumableArray(arr){return _arrayWithoutHoles(arr)||_iterableToArray(arr)||_unsupportedIterableToArray(arr)||_nonIterableSpread();}
function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}
function _unsupportedIterableToArray(o,minLen){if(!o)return;if(typeof o==="string")return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);if(n==="Object"&&o.constructor)n=o.constructor.name;if(n==="Map"||n==="Set")return Array.from(o);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen);}
function _iterableToArray(iter){if(typeof Symbol!=="undefined"&&iter[Symbol.iterator]!=null||iter["@@iterator"]!=null)return Array.from(iter);}
function _arrayWithoutHoles(arr){if(Array.isArray(arr))return _arrayLikeToArray(arr);}
function _arrayLikeToArray(arr,len){if(len==null||len>arr.length)len=arr.length;for(var i=0,arr2=new Array(len);i<len;i++){arr2[i]=arr[i];}return arr2;}
(function($,window,Drupal,drupalSettings,_ref){var isFocusable=_ref.isFocusable,tabbable=_ref.tabbable;Drupal.behaviors.AJAX={attach:function attach(context,settings){function loadAjaxBehavior(base){var elementSettings=settings.ajax[base];if(typeof elementSettings.selector==='undefined'){elementSettings.selector="#".concat(base);}
once('drupal-ajax',$(elementSettings.selector)).forEach(function(el){elementSettings.element=el;elementSettings.base=base;Drupal.ajax(elementSettings);});}
Object.keys(settings.ajax||{}).forEach(function(base){return loadAjaxBehavior(base);});Drupal.ajax.bindAjaxLinks(document.body);once('ajax','.use-ajax-submit').forEach(function(el){var elementSettings={};elementSettings.url=$(el.form).attr('action');elementSettings.setClick=true;elementSettings.event='click';elementSettings.progress={type:'throbber'};elementSettings.base=el.id;elementSettings.element=el;Drupal.ajax(elementSettings);});},detach:function detach(context,settings,trigger){if(trigger==='unload'){Drupal.ajax.expired().forEach(function(instance){Drupal.ajax.instances[instance.instanceIndex]=null;});}}};Drupal.AjaxError=function(xmlhttp,uri,customMessage){var statusCode;var statusText;var responseText;if(xmlhttp.status){statusCode="\n".concat(Drupal.t('An AJAX HTTP error occurred.'),"\n").concat(Drupal.t('HTTP Result Code: !status',{'!status':xmlhttp.status}));}else{statusCode="\n".concat(Drupal.t('An AJAX HTTP request terminated abnormally.'));}
statusCode+="\n".concat(Drupal.t('Debugging information follows.'));var pathText="\n".concat(Drupal.t('Path: !uri',{'!uri':uri}));statusText='';try{statusText="\n".concat(Drupal.t('StatusText: !statusText',{'!statusText':xmlhttp.statusText.trim()}));}catch(e){}
responseText='';try{responseText="\n".concat(Drupal.t('ResponseText: !responseText',{'!responseText':xmlhttp.responseText.trim()}));}catch(e){}
responseText=responseText.replace(/<("[^"]*"|'[^']*'|[^'">])*>/gi,'');responseText=responseText.replace(/[\n]+\s+/g,'\n');var readyStateText=xmlhttp.status===0?"\n".concat(Drupal.t('ReadyState: !readyState',{'!readyState':xmlhttp.readyState})):'';customMessage=customMessage?"\n".concat(Drupal.t('CustomMessage: !customMessage',{'!customMessage':customMessage})):'';this.message=statusCode+pathText+statusText+customMessage+responseText+readyStateText;this.name='AjaxError';};Drupal.AjaxError.prototype=new Error();Drupal.AjaxError.prototype.constructor=Drupal.AjaxError;Drupal.ajax=function(settings){if(arguments.length!==1){throw new Error('Drupal.ajax() function must be called with one configuration object only');}
var base=settings.base||false;var element=settings.element||false;delete settings.base;delete settings.element;if(!settings.progress&&!element){settings.progress=false;}
var ajax=new Drupal.Ajax(base,element,settings);ajax.instanceIndex=Drupal.ajax.instances.length;Drupal.ajax.instances.push(ajax);return ajax;};Drupal.ajax.instances=[];Drupal.ajax.expired=function(){return Drupal.ajax.instances.filter(function(instance){return instance&&instance.element!==false&&!document.body.contains(instance.element);});};Drupal.ajax.bindAjaxLinks=function(element){once('ajax','.use-ajax',element).forEach(function(ajaxLink){var $linkElement=$(ajaxLink);var elementSettings={progress:{type:'throbber'},dialogType:$linkElement.data('dialog-type'),dialog:$linkElement.data('dialog-options'),dialogRenderer:$linkElement.data('dialog-renderer'),base:$linkElement.attr('id'),element:ajaxLink};var href=$linkElement.attr('href');if(href){elementSettings.url=href;elementSettings.event='click';}
Drupal.ajax(elementSettings);});};Drupal.Ajax=function(base,element,elementSettings){var defaults={event:element?'mousedown':null,keypress:true,selector:base?"#".concat(base):null,effect:'none',speed:'none',method:'replaceWith',progress:{type:'throbber',message:Drupal.t('Please wait...')},submit:{js:true}};$.extend(this,defaults,elementSettings);this.commands=new Drupal.AjaxCommands();this.instanceIndex=false;if(this.wrapper){this.wrapper="#".concat(this.wrapper);}
this.element=element;this.element_settings=elementSettings;this.elementSettings=elementSettings;if(this.element&&this.element.form){this.$form=$(this.element.form);}
if(!this.url){var $element=$(this.element);if($element.is('a')){this.url=$element.attr('href');}else if(this.element&&element.form){this.url=this.$form.attr('action');}}
var originalUrl=this.url;this.url=this.url.replace(/\/nojs(\/|$|\?|#)/,'/ajax$1');if(drupalSettings.ajaxTrustedUrl[originalUrl]){drupalSettings.ajaxTrustedUrl[this.url]=true;}
var ajax=this;ajax.options={url:ajax.url,data:ajax.submit,beforeSerialize:function beforeSerialize(elementSettings,options){return ajax.beforeSerialize(elementSettings,options);},beforeSubmit:function beforeSubmit(formValues,elementSettings,options){ajax.ajaxing=true;return ajax.beforeSubmit(formValues,elementSettings,options);},beforeSend:function beforeSend(xmlhttprequest,options){ajax.ajaxing=true;return ajax.beforeSend(xmlhttprequest,options);},success:function success(response,status,xmlhttprequest){if(typeof response==='string'){response=$.parseJSON(response);}
if(response!==null&&!drupalSettings.ajaxTrustedUrl[ajax.url]){if(xmlhttprequest.getResponseHeader('X-Drupal-Ajax-Token')!=='1'){var customMessage=Drupal.t('The response failed verification so will not be processed.');return ajax.error(xmlhttprequest,ajax.url,customMessage);}}
return ajax.success(response,status);},complete:function complete(xmlhttprequest,status){ajax.ajaxing=false;if(status==='error'||status==='parsererror'){return ajax.error(xmlhttprequest,ajax.url);}},dataType:'json',jsonp:false,type:'POST'};if(elementSettings.dialog){ajax.options.data.dialogOptions=elementSettings.dialog;}
if(ajax.options.url.indexOf('?')===-1){ajax.options.url+='?';}else{ajax.options.url+='&';}
var wrapper="drupal_".concat(elementSettings.dialogType||'ajax');if(elementSettings.dialogRenderer){wrapper+=".".concat(elementSettings.dialogRenderer);}
ajax.options.url+="".concat(Drupal.ajax.WRAPPER_FORMAT,"=").concat(wrapper);$(ajax.element).on(elementSettings.event,function(event){if(!drupalSettings.ajaxTrustedUrl[ajax.url]&&!Drupal.url.isLocal(ajax.url)){throw new Error(Drupal.t('The callback URL is not local and not trusted: !url',{'!url':ajax.url}));}
return ajax.eventResponse(this,event);});if(elementSettings.keypress){$(ajax.element).on('keypress',function(event){return ajax.keypressResponse(this,event);});}
if(elementSettings.prevent){$(ajax.element).on(elementSettings.prevent,false);}};Drupal.ajax.WRAPPER_FORMAT='_wrapper_format';Drupal.Ajax.AJAX_REQUEST_PARAMETER='_drupal_ajax';Drupal.Ajax.prototype.execute=function(){if(this.ajaxing){return;}
try{this.beforeSerialize(this.element,this.options);return $.ajax(this.options);}catch(e){this.ajaxing=false;window.alert("An error occurred while attempting to process ".concat(this.options.url,": ").concat(e.message));return $.Deferred().reject();}};Drupal.Ajax.prototype.keypressResponse=function(element,event){var ajax=this;if(event.which===13||event.which===32&&element.type!=='text'&&element.type!=='textarea'&&element.type!=='tel'&&element.type!=='number'){event.preventDefault();event.stopPropagation();$(element).trigger(ajax.elementSettings.event);}};Drupal.Ajax.prototype.eventResponse=function(element,event){event.preventDefault();event.stopPropagation();var ajax=this;if(ajax.ajaxing){return;}
try{if(ajax.$form){if(ajax.setClick){element.form.clk=element;}
ajax.$form.ajaxSubmit(ajax.options);}else{ajax.beforeSerialize(ajax.element,ajax.options);$.ajax(ajax.options);}}catch(e){ajax.ajaxing=false;window.alert("An error occurred while attempting to process ".concat(ajax.options.url,": ").concat(e.message));}};Drupal.Ajax.prototype.beforeSerialize=function(element,options){if(this.$form&&document.body.contains(this.$form.get(0))){var settings=this.settings||drupalSettings;Drupal.detachBehaviors(this.$form.get(0),settings,'serialize');}
options.data[Drupal.Ajax.AJAX_REQUEST_PARAMETER]=1;var pageState=drupalSettings.ajaxPageState;options.data['ajax_page_state[theme]']=pageState.theme;options.data['ajax_page_state[theme_token]']=pageState.theme_token;options.data['ajax_page_state[libraries]']=pageState.libraries;};Drupal.Ajax.prototype.beforeSubmit=function(formValues,element,options){};Drupal.Ajax.prototype.beforeSend=function(xmlhttprequest,options){if(this.$form){options.extraData=options.extraData||{};options.extraData.ajax_iframe_upload='1';var v=$.fieldValue(this.element);if(v!==null){options.extraData[this.element.name]=v;}}
$(this.element).prop('disabled',true);if(!this.progress||!this.progress.type){return;}
var progressIndicatorMethod="setProgressIndicator".concat(this.progress.type.slice(0,1).toUpperCase()).concat(this.progress.type.slice(1).toLowerCase());if(progressIndicatorMethod in this&&typeof this[progressIndicatorMethod]==='function'){this[progressIndicatorMethod].call(this);}};Drupal.theme.ajaxProgressThrobber=function(message){var messageMarkup=typeof message==='string'?Drupal.theme('ajaxProgressMessage',message):'';var throbber='<div class="throbber">&nbsp;</div>';return"<div class=\"ajax-progress ajax-progress-throbber\">".concat(throbber).concat(messageMarkup,"</div>");};Drupal.theme.ajaxProgressIndicatorFullscreen=function(){return'<div class="ajax-progress ajax-progress-fullscreen">&nbsp;</div>';};Drupal.theme.ajaxProgressMessage=function(message){return"<div class=\"message\">".concat(message,"</div>");};Drupal.theme.ajaxProgressBar=function($element){return $('<div class="ajax-progress ajax-progress-bar"></div>').append($element);};Drupal.Ajax.prototype.setProgressIndicatorBar=function(){var progressBar=new Drupal.ProgressBar("ajax-progress-".concat(this.element.id),$.noop,this.progress.method,$.noop);if(this.progress.message){progressBar.setProgress(-1,this.progress.message);}
if(this.progress.url){progressBar.startMonitoring(this.progress.url,this.progress.interval||1500);}
this.progress.element=$(Drupal.theme('ajaxProgressBar',progressBar.element));this.progress.object=progressBar;$(this.element).after(this.progress.element);};Drupal.Ajax.prototype.setProgressIndicatorThrobber=function(){this.progress.element=$(Drupal.theme('ajaxProgressThrobber',this.progress.message));$(this.element).after(this.progress.element);};Drupal.Ajax.prototype.setProgressIndicatorFullscreen=function(){this.progress.element=$(Drupal.theme('ajaxProgressIndicatorFullscreen'));$('body').append(this.progress.element);};Drupal.Ajax.prototype.success=function(response,status){var _this=this;if(this.progress.element){$(this.progress.element).remove();}
if(this.progress.object){this.progress.object.stopMonitoring();}
$(this.element).prop('disabled',false);var elementParents=$(this.element).parents('[data-drupal-selector]').addBack().toArray();var focusChanged=false;Object.keys(response||{}).forEach(function(i){if(response[i].command&&_this.commands[response[i].command]){_this.commands[response[i].command](_this,response[i],status);if(response[i].command==='invoke'&&response[i].method==='focus'||response[i].command==='focusFirst'){focusChanged=true;}}});if(!focusChanged&&this.element&&!$(this.element).data('disable-refocus')){var target=false;for(var n=elementParents.length-1;!target&&n>=0;n--){target=document.querySelector("[data-drupal-selector=\"".concat(elementParents[n].getAttribute('data-drupal-selector'),"\"]"));}
if(target){$(target).trigger('focus');}}
if(this.$form&&document.body.contains(this.$form.get(0))){var settings=this.settings||drupalSettings;Drupal.attachBehaviors(this.$form.get(0),settings);}
this.settings=null;};Drupal.Ajax.prototype.getEffect=function(response){var type=response.effect||this.effect;var speed=response.speed||this.speed;var effect={};if(type==='none'){effect.showEffect='show';effect.hideEffect='hide';effect.showSpeed='';}else if(type==='fade'){effect.showEffect='fadeIn';effect.hideEffect='fadeOut';effect.showSpeed=speed;}else{effect.showEffect="".concat(type,"Toggle");effect.hideEffect="".concat(type,"Toggle");effect.showSpeed=speed;}
return effect;};Drupal.Ajax.prototype.error=function(xmlhttprequest,uri,customMessage){if(this.progress.element){$(this.progress.element).remove();}
if(this.progress.object){this.progress.object.stopMonitoring();}
$(this.wrapper).show();$(this.element).prop('disabled',false);if(this.$form&&document.body.contains(this.$form.get(0))){var settings=this.settings||drupalSettings;Drupal.attachBehaviors(this.$form.get(0),settings);}
throw new Drupal.AjaxError(xmlhttprequest,uri,customMessage);};Drupal.theme.ajaxWrapperNewContent=function($newContent,ajax,response){return(response.effect||ajax.effect)!=='none'&&$newContent.filter(function(i){return!($newContent[i].nodeName==='#comment'||$newContent[i].nodeName==='#text'&&/^(\s|\n|\r)*$/.test($newContent[i].textContent));}).length>1?Drupal.theme('ajaxWrapperMultipleRootElements',$newContent):$newContent;};Drupal.theme.ajaxWrapperMultipleRootElements=function($elements){return $('<div></div>').append($elements);};Drupal.AjaxCommands=function(){};Drupal.AjaxCommands.prototype={insert:function insert(ajax,response){var $wrapper=response.selector?$(response.selector):$(ajax.wrapper);var method=response.method||ajax.method;var effect=ajax.getEffect(response);var settings=response.settings||ajax.settings||drupalSettings;var $newContent=$($.parseHTML(response.data,document,true));$newContent=Drupal.theme('ajaxWrapperNewContent',$newContent,ajax,response);switch(method){case'html':case'replaceWith':case'replaceAll':case'empty':case'remove':Drupal.detachBehaviors($wrapper.get(0),settings);break;default:break;}
$wrapper[method]($newContent);if(effect.showEffect!=='show'){$newContent.hide();}
var $ajaxNewContent=$newContent.find('.ajax-new-content');if($ajaxNewContent.length){$ajaxNewContent.hide();$newContent.show();$ajaxNewContent[effect.showEffect](effect.showSpeed);}else if(effect.showEffect!=='show'){$newContent[effect.showEffect](effect.showSpeed);}
if($newContent.parents('html').length){$newContent.each(function(index,element){if(element.nodeType===Node.ELEMENT_NODE){Drupal.attachBehaviors(element,settings);}});}},remove:function remove(ajax,response,status){var settings=response.settings||ajax.settings||drupalSettings;$(response.selector).each(function(){Drupal.detachBehaviors(this,settings);}).remove();},changed:function changed(ajax,response,status){var $element=$(response.selector);if(!$element.hasClass('ajax-changed')){$element.addClass('ajax-changed');if(response.asterisk){$element.find(response.asterisk).append(" <abbr class=\"ajax-changed\" title=\"".concat(Drupal.t('Changed'),"\">*</abbr> "));}}},alert:function alert(ajax,response,status){window.alert(response.text);},announce:function announce(ajax,response){if(response.priority){Drupal.announce(response.text,response.priority);}else{Drupal.announce(response.text);}},redirect:function redirect(ajax,response,status){window.location=response.url;},css:function css(ajax,response,status){$(response.selector).css(response.argument);},settings:function settings(ajax,response,status){var ajaxSettings=drupalSettings.ajax;if(ajaxSettings){Drupal.ajax.expired().forEach(function(instance){if(instance.selector){var selector=instance.selector.replace('#','');if(selector in ajaxSettings){delete ajaxSettings[selector];}}});}
if(response.merge){$.extend(true,drupalSettings,response.settings);}else{ajax.settings=response.settings;}},data:function data(ajax,response,status){$(response.selector).data(response.name,response.value);},focusFirst:function focusFirst(ajax,response,status){var focusChanged=false;var container=document.querySelector(response.selector);if(container){var tabbableElements=tabbable(container);if(tabbableElements.length){tabbableElements[0].focus();focusChanged=true;}else if(isFocusable(container)){container.focus();focusChanged=true;}}
if(ajax.hasOwnProperty('element')&&!focusChanged){ajax.element.focus();}},invoke:function invoke(ajax,response,status){var $element=$(response.selector);$element[response.method].apply($element,_toConsumableArray(response.args));},restripe:function restripe(ajax,response,status){$(response.selector).find('> tbody > tr:visible, > tr:visible').removeClass('odd even').filter(':even').addClass('odd').end().filter(':odd').addClass('even');},update_build_id:function update_build_id(ajax,response,status){$("input[name=\"form_build_id\"][value=\"".concat(response.old,"\"]")).val(response.new);},add_css:function add_css(ajax,response,status){$('head').prepend(response.data);},message:function message(ajax,response){var messages=new Drupal.Message(document.querySelector(response.messageWrapperQuerySelector));if(response.clearPrevious){messages.clear();}
messages.add(response.message,response.messageOptions);}};})(jQuery,window,Drupal,drupalSettings,window.tabbable);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/core/misc/ajax.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.submit_once.js. */
(function($,Drupal){'use strict';Drupal.behaviors.webformSubmitOnce={clear:function(){var $form=$('.js-webform-submit-once');$form.removeData('webform-submitted');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').removeClass('is-disabled');$form.find('.form-actions .ajax-progress.ajax-progress-throbber').remove();},attach:function(context){$('.js-webform-submit-once',context).once('webform-submit-once').each(function(){var $form=$(this);$form.removeData('webform-submitted');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').removeClass('js-webform-submit-clicked');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').on('click',function(){$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').removeClass('js-webform-submit-clicked');$(this).addClass('js-webform-submit-clicked');});$(this).on('submit',function(){var $clickedButton=$form.find('.js-webform-wizard-pages-links :submit.js-webform-submit-clicked, .form-actions :submit.js-webform-submit-clicked');if(!$clickedButton.attr('formnovalidate')&&$.isFunction(jQuery.fn.valid)&&!($form.valid())){return false;}
if($form.data('webform-submitted')){return false;}
$form.data('webform-submitted','true');$form.find('.js-webform-wizard-pages-links :submit, .form-actions :submit').addClass('is-disabled');$clickedButton.after(Drupal.theme.ajaxProgressThrobber());});});}};})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.form.submit_once.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.element.message.js. */
(function($,Drupal){'use strict';var hasLocalStorage=(function(){try{localStorage.setItem('webform','webform');localStorage.removeItem('webform');return true;}
catch(e){return false;}}());var hasSessionStorage=(function(){try{sessionStorage.setItem('webform','webform');sessionStorage.removeItem('webform');return true;}
catch(e){return false;}}());Drupal.behaviors.webformMessageClose={attach:function(context){$(context).find('.js-webform-message--close').once('webform-message--close').each(function(){var $element=$(this);var id=$element.attr('data-message-id');var storage=$element.attr('data-message-storage');var effect=$element.attr('data-message-close-effect')||'hide';switch(effect){case'slide':effect='slideUp';break;case'fade':effect='fadeOut';break;}
if(isClosed($element,storage,id)){return;}
if($element.attr('style')!=='display: none;'){$element.show();}
$element.find('.js-webform-message__link').on('click',function(event){$element[effect]();setClosed($element,storage,id);$element.trigger('close');event.preventDefault();});});}};function isClosed($element,storage,id){if(!id||!storage){return false;}
switch(storage){case'local':if(hasLocalStorage){return localStorage.getItem('Drupal.webform.message.'+id)||false;}
return false;case'session':if(hasSessionStorage){return sessionStorage.getItem('Drupal.webform.message.'+id)||false;}
return false;default:return false;}}
function setClosed($element,storage,id){if(!id||!storage){return;}
switch(storage){case'local':if(hasLocalStorage){localStorage.setItem('Drupal.webform.message.'+id,true);}
break;case'session':if(hasSessionStorage){sessionStorage.setItem('Drupal.webform.message.'+id,true);}
break;case'user':case'state':case'custom':$.get($element.find('.js-webform-message__link').attr('href'));return true;}}})(jQuery,Drupal);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/webform/js/webform.element.message.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/modules/contrib/antibot/js/antibot.js. */
(function(Drupal,drupalSettings){"use strict";Drupal.antibot={};Drupal.behaviors.antibot={attach:function(context){drupalSettings.antibot.human=false;document.body.addEventListener('mousemove',function(){Drupal.antibot.unlockForms();});document.body.addEventListener('touchmove',function(){Drupal.antibot.unlockForms();});document.body.addEventListener('keydown',function(e){if((e.code=='Tab')||(e.code=='Enter')){Drupal.antibot.unlockForms();}});}};Drupal.antibot.unlockForms=function(){if(!drupalSettings.antibot.human){if(drupalSettings.antibot.forms!=undefined){Object.values(drupalSettings.antibot.forms).forEach(function(config){const form=document.getElementById(config.id);if(form){form.setAttribute('action',form.getAttribute('data-action'));const input=form.querySelector('input[name="antibot_key"]');if(input){input.value=config.key;}}});}
drupalSettings.antibot.human=true;}};})(Drupal,drupalSettings);
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/modules/contrib/antibot/js/antibot.js. */;
/* Source and licensing information for the line(s) below can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/libraries/collapse/collapse.js. */
!function(e,s){"object"==typeof exports&&"undefined"!=typeof module?module.exports=s():"function"==typeof define&&define.amd?define(s):(e="undefined"!=typeof globalThis?globalThis:e||self).Collapse=s()}(this,(function(){"use strict";class Collapse{static defaultOptions={openClass:"is-open",$handlers:null};constructor(e,s){"string"==typeof e&&(e=document.querySelector(e)),this.$el=e,this.$el.collapse=this,this._events=[],this.options={...Collapse.defaultOptions,...s},this.isOpen=!1,this.$handlers=[];let{$handlers:t}=this.options;"string"==typeof t&&(t=document.querySelectorAll(this.options.$handlers)),!1===Array.isArray(t)&&(t=t?[t]:[]),Array.from(document.querySelectorAll("[data-collapse-handler]")).forEach((e=>{Array.from(document.querySelectorAll(e.dataset.collapseHandler)).filter((e=>e===this.$el)).length>0&&t.push(e)})),t.forEach((e=>{this.addHandler(e)}))}deconstructor(){this.$handlers.forEach((e=>{this.removeHandler(e)})),delete this.$el.collapse,this.$el=null,this.options=null,this._events=null,this.handlers=null}on(e,s,t){this._events.find((l=>l.$el===e&&l.type===s&&l.callback===t))&&this.off(e,s,t),this._events.push({$el:e,type:s,callback:t}),e.addEventListener(s,t)}off(e,s,t=null){this._events.filter((l=>l.$el===e&&l.type===s&&(!t||l.callback===t))).forEach((t=>{const l=this._events.indexOf(t);e.removeEventListener(s,t.callback),this._events.splice(l,1)}))}handleToggle(e){this.toggle(),e.preventDefault()}addHandler(e){this.on(e,"click",this.handleToggle.bind(this)),this.$handlers.push(e)}removeHandler(e){const s=this.$handlers.indexOf(e);-1!==s&&(this.off(e,"click"),this.$handlers.splice(s,1))}toggle(){this.isOpen?this.close():this.open()}open(){this.$handlers.forEach((e=>{e.setAttribute("aria-expanded","true")})),this.options.openClass&&this.$el.classList.add(this.options.openClass),this.isOpen=!0;const e=new CustomEvent("open.collapse");this.$el.dispatchEvent(e)}close(){this.$handlers.forEach((e=>{e.setAttribute("aria-expanded","false")})),this.options.openClass&&this.$el.classList.remove(this.options.openClass),this.isOpen=!1;const e=new CustomEvent("close.collapse");this.$el.dispatchEvent(e)}}return Collapse}));
/* Source and licensing information for the above line(s) can be found at https://www.consuwijzer.nl/themes/custom/consuwijzer/dist/js/libraries/collapse/collapse.js. */;
