// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/4.24/esri/copyright.txt for details.//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../Color ../../core/Error ../../core/screenUtils ./gfxUtils ./previewUtils ./renderUtils ../../views/support/colorUtils".split(" "),function(w,A,B,I,p,t,q,J,C){function K(a){if(0===a.length)return 0;if(2<a.length){const b=p.px2pt(1),c=parseFloat(a);switch(a.slice(-2)){case "px":return c;case "pt":return c*b;case "in":return 72*c*b;case "pc":return 12*c*b;case "mm":return c*L*b;case "cm":return c*M*b}}return parseFloat(a)}function D(a){var b=
null==a?void 0:a.size;a=null!=b&&"object"===typeof b&&"width"in b?p.pt2px(b.width):null;b=null!=b&&"object"===typeof b&&"height"in b?p.pt2px(b.height):null;return{width:a,height:b}}function N(a,b){return y.apply(this,arguments)}function y(){y=A._asyncToGenerator(function*(a,b){const c=b.fill,l=a.color;"pattern"===(null==c?void 0:c.type)&&l&&"picture-fill"!==a.type&&(a=yield t.getPatternUrlWithColor(c.src,l.toCss(!0)),c.src=a,b.fill=c)});return y.apply(this,arguments)}function E(a,b){return a>b?"dark":
"light"}function F(a,b){var c,l,n="number"===typeof(null==b?void 0:b.size)?null==b?void 0:b.size:null,f=null!=n?p.pt2px(n):null,m=null!=(null==b?void 0:b.maxSize)?p.pt2px(b.maxSize):null;n=null!=(null==b?void 0:b.rotation)?b.rotation:"angle"in a?a.angle:null;var k=t.getFill(a),h=t.getStroke(a);"dark"!==G(a,245)||null!=b&&b.ignoreWhiteSymbols||(h={width:.75,...h,color:"#bdc3c7"});k={shape:null,fill:k,stroke:h,offset:[0,0]};null!=(c=h)&&c.width&&(h.width=Math.min(h.width,H));var g=(null==(l=h)?void 0:
l.width)||0;c=null==(null==b?void 0:b.size)?!1:null!=(null==b?void 0:b.scale)?null==b?void 0:b.scale:!0;var e=0,d=0;l=!1;switch(a.type){case "simple-marker":var r=a.style;d=e=m=Math.min(null!=f?f:p.pt2px(a.size),m||x);switch(r){case "circle":k.shape={type:"circle",cx:0,cy:0,r:.5*m};c||(e+=g,d+=g);break;case "cross":k.shape={type:"path",path:[{command:"M",values:[0,.5*d]},{command:"L",values:[e,.5*d]},{command:"M",values:[.5*e,0]},{command:"L",values:[.5*e,d]}]};break;case "diamond":k.shape={type:"path",
path:[{command:"M",values:[0,.5*d]},{command:"L",values:[.5*e,0]},{command:"L",values:[e,.5*d]},{command:"L",values:[.5*e,d]},{command:"Z",values:[]}]};c||(e+=g,d+=g);break;case "square":k.shape={type:"path",path:[{command:"M",values:[0,0]},{command:"L",values:[e,0]},{command:"L",values:[e,d]},{command:"L",values:[0,d]},{command:"Z",values:[]}]};c||(e+=g,d+=g);n&&(l=!0);break;case "triangle":k.shape={type:"path",path:[{command:"M",values:[.5*e,0]},{command:"L",values:[e,d]},{command:"L",values:[0,
d]},{command:"Z",values:[]}]};c||(e+=g,d+=g);n&&(l=!0);break;case "x":k.shape={type:"path",path:[{command:"M",values:[0,0]},{command:"L",values:[e,d]},{command:"M",values:[e,0]},{command:"L",values:[0,d]}]};n&&(l=!0);break;case "path":k.shape={type:"path",path:a.path||""},c||(e+=g,d+=g),n&&(l=!0),c=!0}break;case "simple-line":{const {width:u,height:v}=D(b);a=null!=v?v:Math.min(null!=f?f:g,m||H);c=null!=u?u:O;h.width=a;e=c;d=a;m=(null==k?void 0:null==(r=k.stroke)?void 0:r.cap)||"butt";f="round"===
m;c=!0;k.stroke.cap="butt"===m?"square":m;k.shape={type:"path",path:[{command:"M",values:[f?a/2:0,d/2]},{command:"L",values:[f?e-a/2:e,d/2]}]};break}case "picture-fill":case "simple-fill":{a="object"===typeof(null==b?void 0:b.symbolConfig)&&(null==b?void 0:b.symbolConfig.isSquareFill);const {width:u,height:v}=D(b);e=a&&null!=u?u:null!=f?f:P;d=a&&null!=v?v:e;c||(e+=g,d+=g);c=!0;k.shape=a?{type:"path",path:[{command:"M",values:[0,0]},{command:"L",values:[e,0]},{command:"L",values:[e,d]},{command:"L",
values:[0,d]},{command:"L",values:[0,0]},{command:"Z",values:[]}]}:q.shapes.fill[0];break}case "picture-marker":e=p.pt2px(a.width);d=p.pt2px(a.height);f=null!=f?f:Math.max(e,d);d=e/d;e=1>=d?Math.ceil(f*d):f;d=1>=d?f:Math.ceil(f/d);e=Math.min(e,m||x);d=Math.min(d,m||x);k.shape={type:"image",x:-Math.round(e/2),y:-Math.round(d/2),width:e,height:d,src:a.url||""};n&&(l=!0);break;case "text":r=a.text||"Aa",h=a.font,m=Math.min(null!=f?f:p.pt2px(h.size),m||x),e=r,d={weight:h.weight,size:m,family:h.family},
f=Q.getContext("2d"),g=[],d&&(d.weight&&g.push(d.weight),d.size&&g.push(d.size+"px"),d.family&&g.push(d.family)),f.font=g.join(" "),e=f.measureText(e).width,e=(f=/[\uE600-\uE6FF]/.test(r))?m:e,d=m,g=.25*K((h?m:0).toString()),f&&(g+=5),k.shape={type:"text",text:r,x:a.xoffset||0,y:a.yoffset||g,align:"middle",alignBaseline:a.verticalAlignment,decoration:h&&h.decoration,rotated:a.rotated,kerning:a.kerning},k.font=h&&{size:m,style:h.style,decoration:h.decoration,weight:h.weight,family:h.family}}return{shapeDescriptor:k,
size:[e,d],renderOptions:{node:null==b?void 0:b.node,scale:c,opacity:null==b?void 0:b.opacity,rotation:n,useRotationSize:l,effectView:null==b?void 0:b.effectView}}}function z(){z=A._asyncToGenerator(function*(a,b){const {shapeDescriptor:c,size:l,renderOptions:n}=F(a,b);if(!c.shape)throw new I("symbolPreview: renderPreviewHTML2D","symbol not supported.");yield N(a,c);a=[[c]];"object"===typeof(null==b?void 0:b.symbolConfig)&&null!=b&&b.symbolConfig.applyColorModulation&&(b=.6*l[0],a.unshift([{...c,
offset:[-b,0],fill:q.adjustColorBrightness(c.fill,-.3)}]),a.push([{...c,offset:[b,0],fill:q.adjustColorBrightness(c.fill,.3)}]),l[0]+=2*b,n.scale=!1);return J.renderSymbol(a,l,n)});return z.apply(this,arguments)}function G(a,b=225){var c=t.getFill(a);a=t.getStroke(a);c=!c||"type"in c?null:new B(c);a=null!=a&&a.color?new B(null==a?void 0:a.color):null;c=c?E(C.getColorLuminance(c),b):null;return(a=a?E(C.getColorLuminance(a),b):null)?c?c===a?c:225<=b?"light":"dark":a:c}const P=q.SymbolSizeDefaults.size,
x=q.SymbolSizeDefaults.maxSize,H=q.SymbolSizeDefaults.maxOutlineSize,O=q.SymbolSizeDefaults.lineWidth,Q=document.createElement("canvas"),L=7.2/2.54,M=72/2.54;w.getContrastingBackgroundTheme=G;w.getRenderSymbolParameters=F;w.previewSymbol2D=function(a,b){return z.apply(this,arguments)};Object.defineProperties(w,{__esModule:{value:!0},[Symbol.toStringTag]:{value:"Module"}})});