//>>built
define("esri/layers/ServiceGeneratedFeatureCollection","dojo/_base/declare dojo/_base/connect dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-style dojo/has ../kernel ../SpatialReference ../geometry/Extent ../geometry/webMercatorUtils ../renderers/SimpleRenderer ./layer ./FeatureLayer ../dijit/PopupTemplate".split(" "),function(h,r,e,f,n,t,B,u,v,w,p,m,x,y,z){h=h([x],{declaredClass:"esri.layers._ServiceGeneratedFeatureCollection",constructor:function(a,b){this.pointSymbol=b&&b.pointSymbol;
this.polylineSymbol=b&&b.polylineSymbol;this.polygonSymbol=b&&b.polygonSymbol;this._outSR=b&&(b.outSpatialReference||b.outSR)||new v({wkid:4326});this._options=e.mixin({},b)},parse:function(){},getFeatureLayers:function(){var a=[];this._fLayers&&(a=a.concat(this._fLayers));return a},onRefresh:function(){},onOpacityChange:function(){},refresh:function(){this.loaded&&this._map&&!this._io&&this.visible&&this._createLayer()},_createLayer:function(a){var b=this;this._fireUpdateStart();a=this.parse(a);
a.addCallback(function(c){b._io=null;b._initLayer(c)});a.addErrback(function(c){b._io=null;c=e.mixin(Error(),c);c.message="Unable to load resource: "+b.url+" "+(c.message||"");b._fireUpdateEnd(c);b.onError(c)})},_initLayer:function(a){this.loaded&&this._removeInternalLayers();this.name=a.name;this.description=a.description;this.snippet=a.snippet;this.featureInfos=a.featureInfos;this.fullExtent=this.initialExtent=new w(a.lookAtExtent);this.copyright=a.author||a.copyright;var b;(a=e.getObject("featureCollection.layers",
!1,a))&&0<a.length&&(this._fLayers=[],f.forEach(a,function(c,k){var d=e.getObject("featureSet.features",!1,c);d&&0<d.length&&(b=e.mixin({outFields:["*"],infoTemplate:c.popupInfo?new z(c.popupInfo):null,editable:!1},this._options),b.id&&(b.id=b.id+"_"+k),b.webgl=!1,c.layerDefinition.capabilities="Query,Data",d=new y(c,b),d.geometryType&&(this["_"+d.geometryType]=d),this._fLayers.push(d))},this),0===this._fLayers.length&&delete this._fLayers);this.items=[];this._esriGeometryPoint&&(this.items=this.items.concat(this._esriGeometryPoint.graphics),
this.pointSymbol&&(a=new m(this.pointSymbol),this._esriGeometryPoint.setRenderer(a)));this._esriGeometryPolyline&&(this.items=this.items.concat(this._esriGeometryPolyline.graphics),this.polylineSymbol&&(a=new m(this.polylineSymbol),this._esriGeometryPolyline.setRenderer(a)));this._esriGeometryPolygon&&(this.items=this.items.concat(this._esriGeometryPolygon.graphics),this.polygonSymbol&&(a=new m(this.polygonSymbol),this._esriGeometryPolygon.setRenderer(a)));this._fireUpdateEnd();this.loaded&&(this._addInternalLayers(),
this.onRefresh())},_addInternalLayers:function(){var a=this._map;this._fireUpdateStart();var b=a.spatialReference,c=this._outSR;if(b.wkid)var k=b._isWebMercator()&&c._isWebMercator()||b.wkid===c.wkid;else if(b.wkt)k=b.wkt===c.wkt;else return;if(!k)if(b._isWebMercator()&&4326===c.wkid)this._converter=p.geographicToWebMercator;else if(c._isWebMercator()&&4326===b.wkid)this._converter=p.webMercatorToGeographic;else return;(b=this._fLayers)&&0<b.length&&f.forEach(b,function(d){if(this._converter){var l=
d.graphics,g,q,A=l?l.length:0;for(g=0;g<A;g++)(q=l[g].geometry)&&l[g].setGeometry(this._converter(q))}a.addLayer(d)},this);this.setVisibility(this.visible);this._fireUpdateEnd()},_removeInternalLayers:function(){var a=this._map;a&&f.forEach(this.getFeatureLayers(),a.removeLayer,a)},setScaleRange:function(a,b){this.inherited(arguments);f.forEach(this.getFeatureLayers(),function(c){c.setScaleRange(a,b)});this._options.minScale=this.minScale;this._options.maxScale=this.maxScale},setOpacity:function(a){this.opacity!=
a&&(f.forEach(this.getFeatureLayers(),function(b){b.setOpacity(a)}),this.opacity=this._options.opacity=a,this.onOpacityChange(a))},onVisibilityChange:function(a){this._fireUpdateStart();f.forEach(this.getFeatureLayers(),function(b){b.setVisibility(a)});this._fireUpdateEnd()},_setMap:function(a,b){this.inherited(arguments);this._map=a;var c=this._div=n.create("div",null,b);t.set(c,"position","absolute");this._addInternalLayers();this.evaluateSuspension();return c},_unsetMap:function(a,b){this._io&&
this._io.cancel();r.disconnect(this._extChgHandle);delete this._extChgHandle;this._removeInternalLayers();var c=this._div;c&&(b.removeChild(c),n.destroy(c));this._div=null;this.inherited(arguments)}});e.setObject("layers._ServiceGeneratedFeatureCollection",h,u);return h});