//>>built
/*
 *****************************************************************************
Copyright (c) Microsoft Corporation.

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
*****************************************************************************/
var __extends,__assign,__rest,__decorate,__param,__metadata,__awaiter,__generator,__exportStar,__values,__read,__spread,__spreadArrays,__spreadArray,__await,__asyncGenerator,__asyncDelegator,__asyncValues,__makeTemplateObject,__importStar,__importDefault,__classPrivateFieldGet,__classPrivateFieldSet,__createBinding;
(function(l){function q(a,b){a!==r&&("function"===typeof Object.create?Object.defineProperty(a,"__esModule",{value:!0}):a.__esModule=!0);return function(c,d){return a[c]=b?b(c,d):d}}var r="object"===typeof global?global:"object"===typeof self?self:"object"===typeof this?this:{};"function"===typeof define&&define.amd?define("tslib",["exports"],function(a){l(q(r,q(a)))}):"object"===typeof module&&"object"===typeof module.exports?l(q(r,q(module.exports))):l(q(r))})(function(l){var q=Object.setPrototypeOf||
{__proto__:[]}instanceof Array&&function(a,b){a.__proto__=b}||function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};__extends=function(a,b){function c(){this.constructor=a}if("function"!==typeof b&&null!==b)throw new TypeError("Class extends value "+String(b)+" is not a constructor or null");q(a,b);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)};__assign=Object.assign||function(a){for(var b,c=1,d=arguments.length;c<d;c++){b=arguments[c];for(var e in b)Object.prototype.hasOwnProperty.call(b,
e)&&(a[e]=b[e])}return a};__rest=function(a,b){var c={},d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&0>b.indexOf(d)&&(c[d]=a[d]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var e=0;for(d=Object.getOwnPropertySymbols(a);e<d.length;e++)0>b.indexOf(d[e])&&Object.prototype.propertyIsEnumerable.call(a,d[e])&&(c[d[e]]=a[d[e]])}return c};__decorate=function(a,b,c,d){var e=arguments.length,k=3>e?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d,h;if("object"===typeof Reflect&&
"function"===typeof Reflect.decorate)k=Reflect.decorate(a,b,c,d);else for(var f=a.length-1;0<=f;f--)if(h=a[f])k=(3>e?h(k):3<e?h(b,c,k):h(b,c))||k;return 3<e&&k&&Object.defineProperty(b,c,k),k};__param=function(a,b){return function(c,d){b(c,d,a)}};__metadata=function(a,b){if("object"===typeof Reflect&&"function"===typeof Reflect.metadata)return Reflect.metadata(a,b)};__awaiter=function(a,b,c,d){function e(k){return k instanceof c?k:new c(function(h){h(k)})}return new (c||(c=Promise))(function(k,h){function f(m){try{g(d.next(m))}catch(n){h(n)}}
function p(m){try{g(d["throw"](m))}catch(n){h(n)}}function g(m){m.done?k(m.value):e(m.value).then(f,p)}g((d=d.apply(a,b||[])).next())})};__generator=function(a,b){function c(g){return function(m){return d([g,m])}}function d(g){if(k)throw new TypeError("Generator is already executing.");for(;e;)try{if(k=1,h&&(f=g[0]&2?h["return"]:g[0]?h["throw"]||((f=h["return"])&&f.call(h),0):h.next)&&!(f=f.call(h,g[1])).done)return f;if(h=0,f)g=[g[0]&2,f.value];switch(g[0]){case 0:case 1:f=g;break;case 4:return e.label++,
{value:g[1],done:!1};case 5:e.label++;h=g[1];g=[0];continue;case 7:g=e.ops.pop();e.trys.pop();continue;default:if(!(f=e.trys,f=0<f.length&&f[f.length-1])&&(6===g[0]||2===g[0])){e=0;continue}if(3===g[0]&&(!f||g[1]>f[0]&&g[1]<f[3]))e.label=g[1];else if(6===g[0]&&e.label<f[1])e.label=f[1],f=g;else if(f&&e.label<f[2])e.label=f[2],e.ops.push(g);else{f[2]&&e.ops.pop();e.trys.pop();continue}}g=b.call(a,e)}catch(m){g=[6,m],h=0}finally{k=f=0}if(g[0]&5)throw g[1];return{value:g[0]?g[1]:void 0,done:!0}}var e=
{label:0,sent:function(){if(f[0]&1)throw f[1];return f[1]},trys:[],ops:[]},k,h,f,p;return p={next:c(0),"throw":c(1),"return":c(2)},"function"===typeof Symbol&&(p[Symbol.iterator]=function(){return this}),p};__exportStar=function(a,b){for(var c in a)"default"===c||Object.prototype.hasOwnProperty.call(b,c)||__createBinding(b,a,c)};__createBinding=Object.create?function(a,b,c,d){void 0===d&&(d=c);Object.defineProperty(a,d,{enumerable:!0,get:function(){return b[c]}})}:function(a,b,c,d){void 0===d&&(d=
c);a[d]=b[c]};__values=function(a){var b="function"===typeof Symbol&&Symbol.iterator,c=b&&a[b],d=0;if(c)return c.call(a);if(a&&"number"===typeof a.length)return{next:function(){a&&d>=a.length&&(a=void 0);return{value:a&&a[d++],done:!a}}};throw new TypeError(b?"Object is not iterable.":"Symbol.iterator is not defined.");};__read=function(a,b){var c="function"===typeof Symbol&&a[Symbol.iterator];if(!c)return a;var d=c.call(a),e,k=[];try{for(;(void 0===b||0<b--)&&!(e=d.next()).done;)k.push(e.value)}catch(f){var h=
{error:f}}finally{try{e&&!e.done&&(c=d["return"])&&c.call(d)}finally{if(h)throw h.error;}}return k};__spread=function(){for(var a=[],b=0;b<arguments.length;b++)a=a.concat(__read(arguments[b]));return a};__spreadArrays=function(){for(var a=0,b=0,c=arguments.length;b<c;b++)a+=arguments[b].length;a=Array(a);var d=0;for(b=0;b<c;b++)for(var e=arguments[b],k=0,h=e.length;k<h;k++,d++)a[d]=e[k];return a};__spreadArray=function(a,b){for(var c=0,d=b.length,e=a.length;c<d;c++,e++)a[e]=b[c];return a};__await=
function(a){return this instanceof __await?(this.v=a,this):new __await(a)};__asyncGenerator=function(a,b,c){function d(n){p[n]&&(g[n]=function(t){return new Promise(function(u,v){1<m.push([n,t,u,v])||e(n,t)})})}function e(n,t){try{var u=p[n](t);u.value instanceof __await?Promise.resolve(u.value.v).then(k,h):f(m[0][2],u)}catch(v){f(m[0][3],v)}}function k(n){e("next",n)}function h(n){e("throw",n)}function f(n,t){(n(t),m.shift(),m.length)&&e(m[0][0],m[0][1])}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");
var p=c.apply(a,b||[]),g,m=[];return g={},d("next"),d("throw"),d("return"),g[Symbol.asyncIterator]=function(){return this},g};__asyncDelegator=function(a){function b(e,k){c[e]=a[e]?function(h){return(d=!d)?{value:__await(a[e](h)),done:"return"===e}:k?k(h):h}:k}var c,d;return c={},b("next"),b("throw",function(e){throw e;}),b("return"),c[Symbol.iterator]=function(){return this},c};__asyncValues=function(a){function b(k){e[k]=a[k]&&function(h){return new Promise(function(f,p){h=a[k](h);c(f,p,h.done,
h.value)})}}function c(k,h,f,p){Promise.resolve(p).then(function(g){k({value:g,done:f})},h)}if(!Symbol.asyncIterator)throw new TypeError("Symbol.asyncIterator is not defined.");var d=a[Symbol.asyncIterator],e;return d?d.call(a):(a="function"===typeof __values?__values(a):a[Symbol.iterator](),e={},b("next"),b("throw"),b("return"),e[Symbol.asyncIterator]=function(){return this},e)};__makeTemplateObject=function(a,b){Object.defineProperty?Object.defineProperty(a,"raw",{value:b}):a.raw=b;return a};var r=
Object.create?function(a,b){Object.defineProperty(a,"default",{enumerable:!0,value:b})}:function(a,b){a["default"]=b};__importStar=function(a){if(a&&a.__esModule)return a;var b={};if(null!=a)for(var c in a)"default"!==c&&Object.prototype.hasOwnProperty.call(a,c)&&__createBinding(b,a,c);r(b,a);return b};__importDefault=function(a){return a&&a.__esModule?a:{"default":a}};__classPrivateFieldGet=function(a,b,c,d){if("a"===c&&!d)throw new TypeError("Private accessor was defined without a getter");if("function"===
typeof b?a!==b||!d:!b.has(a))throw new TypeError("Cannot read private member from an object whose class did not declare it");return"m"===c?d:"a"===c?d.call(a):d?d.value:b.get(a)};__classPrivateFieldSet=function(a,b,c,d,e){if("m"===d)throw new TypeError("Private method is not writable");if("a"===d&&!e)throw new TypeError("Private accessor was defined without a setter");if("function"===typeof b?a!==b||!e:!b.has(a))throw new TypeError("Cannot write private member to an object whose class did not declare it");
return"a"===d?e.call(a,c):e?e.value=c:b.set(a,c),c};l("__extends",__extends);l("__assign",__assign);l("__rest",__rest);l("__decorate",__decorate);l("__param",__param);l("__metadata",__metadata);l("__awaiter",__awaiter);l("__generator",__generator);l("__exportStar",__exportStar);l("__createBinding",__createBinding);l("__values",__values);l("__read",__read);l("__spread",__spread);l("__spreadArrays",__spreadArrays);l("__spreadArray",__spreadArray);l("__await",__await);l("__asyncGenerator",__asyncGenerator);
l("__asyncDelegator",__asyncDelegator);l("__asyncValues",__asyncValues);l("__makeTemplateObject",__makeTemplateObject);l("__importStar",__importStar);l("__importDefault",__importDefault);l("__classPrivateFieldGet",__classPrivateFieldGet);l("__classPrivateFieldSet",__classPrivateFieldSet)});